/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"
#include "rel/sel/sel.h"

extern u8 lbl_10_bss_493A0[0x5B20];



__declspec(section ".data") u8 lbl_10_bss_493A0[0x5B20] __attribute__((aligned(32)));
