#ifndef REL_MAIN_REL_ACCESSORY_H
#define REL_MAIN_REL_ACCESSORY_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu accessory.c`: globals of accessory.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_bss_88B50: .bss size 0xC00, 8 refs from accessory.c
typedef struct {
    u32 unk_0;  // 4 loads, 4 stores
    u32 unk_4;  // 5 loads, 5 stores
    u32 unk_8;  // 4 loads, 4 stores
    u8 pad_C[0xBF4];
} Obj_1_bss_88B50;
extern Obj_1_bss_88B50 lbl_1_bss_88B50;

// lbl_1_data_3F510: .data size 0x68, 8 refs from accessory.c
extern u8 lbl_1_data_3F510[0x68];

// lbl_1_bss_89760: .bss size 0x10, 3 refs from accessory.c
typedef struct {
    u32 unk_0;  // 0 loads, 5 stores
    u32 unk_4;  // 0 loads, 1 stores
    u32 unk_8;  // 0 loads, 1 stores
    u32 unk_C;  // 0 loads, 1 stores
} Obj_1_bss_89760;
extern Obj_1_bss_89760 lbl_1_bss_89760;

// lbl_1_bss_86ED0: .bss size 0x1C70, 2 refs from accessory.c
typedef struct {
    u8 pad_0[0x8];
    u32 unk_8;  // 7 loads, 0 stores
    u32 unk_C;  // 4 loads, 0 stores
    u32 unk_10;  // 3 loads, 0 stores
    u8 pad_14[0x1C5C];
} Obj_1_bss_86ED0;
extern Obj_1_bss_86ED0 lbl_1_bss_86ED0;

// lbl_1_bss_89770: .bss size 0x10, 2 refs from accessory.c
typedef struct {
    f32 unk_0;  // 1 loads, 4 stores
    u8 pad_4[0xC];
} Obj_1_bss_89770;
extern Obj_1_bss_89770 lbl_1_bss_89770;

// lbl_1_bss_962: .bss size 0x2, 2 refs from accessory.c
extern s16 lbl_1_bss_962;

// lbl_1_bss_89750: .bss size 0x10, 2 refs from accessory.c
typedef struct {
    u32 unk_0;  // 1 loads, 0 stores
    u32 unk_4;  // 1 loads, 0 stores
    u32 unk_8;  // 1 loads, 0 stores
    u8 pad_C[0x4];
} Obj_1_bss_89750;
extern Obj_1_bss_89750 lbl_1_bss_89750;

// lbl_1_data_4059C: .data size 0x24, 1 refs from accessory.c (own data block)
extern u8 lbl_1_data_4059C[0x24];

// jumptable_1_data_405C8: .data size 0x24, 1 refs from accessory.c (own data block)
extern u8 jumptable_1_data_405C8[0x24];

// lbl_1_data_405C0: .data size 0x8, 1 refs from accessory.c (own data block)
extern u32 lbl_1_data_405C0;

// lbl_1_data_405EC: .data size 0x8, 1 refs from accessory.c (own data block)
extern u32 lbl_1_data_405EC;

// lbl_1_data_405F4: .data size 0x6, 1 refs from accessory.c (own data block)
extern u32 lbl_1_data_405F4;

#endif  // REL_MAIN_REL_ACCESSORY_H
