#ifndef REL_MAIN_REL_ALLOC_H
#define REL_MAIN_REL_ALLOC_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu alloc.c`: globals of alloc.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_data_2CDC: .data size 0x10, 9 refs from alloc.c (own data block)
typedef struct {
    u8 unk_0;  // 1 loads, 1 stores
    u8 unk_1;  // 1 loads, 1 stores
    u8 unk_2;  // 0 loads, 1 stores
    u8 unk_3;  // 6 loads, 5 stores
    u16 unk_4;  // 2 loads, 5 stores
    s16 unk_6;  // 2 loads, 1 stores
    u32 unk_8;  // 0 loads, 3 stores
    u32 unk_C;  // 1 loads, 1 stores
} Obj_1_data_2CDC;
extern Obj_1_data_2CDC lbl_1_data_2CDC;

// lbl_1_data_2CD8: .data size 0x4, 4 refs from alloc.c (own data block)
extern u32 lbl_1_data_2CD8;

// lbl_1_bss_F58: .bss size 0x4, 3 refs from alloc.c
extern u32 lbl_1_bss_F58;

// lbl_1_bss_7AC40: .bss size 0x8, 2 refs from alloc.c
extern u32 lbl_1_bss_7AC40[2];

// lbl_1_bss_7AC20: .bss size 0x20, 2 refs from alloc.c
typedef struct {
    u32 unk_0;  // 0 loads, 2 stores
    u8 pad_4[0x1C];
} Obj_1_bss_7AC20;
extern Obj_1_bss_7AC20 lbl_1_bss_7AC20;

// live_camera: .bss size 0x4, 2 refs from alloc.c
typedef struct {
    u8 pad_0[0x2];
    s16 unk_2;  // 2 loads, 0 stores
    u8 pad_4[0x2];
    s16 unk_6;  // 1 loads, 0 stores
    u8 pad_8[0xA4];
    u32 unk_AC;  // 0 loads, 2 stores
    u32 unk_B0;  // 1 loads, 3 stores
    u8 pad_B4[0xC];
    f32 unk_C0;  // 0 loads, 1 stores
    f32 unk_C4;  // 0 loads, 1 stores
    f32 unk_C8;  // 0 loads, 1 stores
    f32 unk_CC;  // 1 loads, 2 stores
    f32 unk_D0;  // 1 loads, 2 stores
    f32 unk_D4;  // 1 loads, 2 stores
    u8 pad_D8[0xC];
    f32 unk_E4;  // 0 loads, 2 stores
    f32 unk_E8;  // 0 loads, 2 stores
    f32 unk_EC;  // 0 loads, 2 stores
} LiveCamera;
extern LiveCamera *live_camera;

// lbl_1_data_3314: .data size 0x1, 1 refs from alloc.c (own data block)
extern u8 lbl_1_data_3314;

// lbl_1_data_32A8: .data size 0xC, 1 refs from alloc.c (own data block)
extern u8 lbl_1_data_32A8[0xC];

// lbl_1_data_2CEC: .data size 0xA, 1 refs from alloc.c (own data block)
extern u8 lbl_1_data_2CEC[0xA];

// lbl_1_data_2CD0: .data size 0x8, 1 refs from alloc.c (own data block)
extern u32 lbl_1_data_2CD0[2];

#endif  // REL_MAIN_REL_ALLOC_H
