#ifndef REL_MAIN_REL_AVLINE_H
#define REL_MAIN_REL_AVLINE_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu avline.c`: globals of avline.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_bss_6C840: .bss size 0x4, 4 refs from avline.c
extern u32 lbl_1_bss_6C840;

// lbl_1_data_1CC74: .data size 0x4, 3 refs from avline.c (own data block)
typedef struct {
    f32 unk_0;  // 3 loads, 0 stores
    f32 unk_4;  // 3 loads, 0 stores
    f32 unk_8;  // 3 loads, 0 stores
} Obj_1_data_1CC74_Target;
extern Obj_1_data_1CC74_Target *lbl_1_data_1CC74;

// lbl_1_bss_6C848: .bss size 0x2, 3 refs from avline.c
extern u8 lbl_1_bss_6C848;

// lbl_1_data_1D514: .data size 0x114, 3 refs from avline.c (own data block)
extern u8 lbl_1_data_1D514[0x114];

// lbl_1_bss_6C844: .bss size 0x2, 3 refs from avline.c
extern u16 lbl_1_bss_6C844;

// lbl_1_data_1C68C: .data size 0x9, 2 refs from avline.c (own data block)
extern u8 lbl_1_data_1C68C[0x9];

// lbl_1_bss_6C84C: .bss size 0x4, 2 refs from avline.c
typedef struct {
    u8 unk_0;  // 7 loads, 4 stores
    u8 pad_1[0x3];
    s16 unk_4;  // 9 loads, 0 stores
    u8 pad_6[0x2];
    u32 unk_8;  // 3 loads, 2 stores
    s16 unk_C;  // 5 loads, 0 stores
    u8 pad_E[0xA];
    s16 unk_18;  // 1 loads, 0 stores
    u16 unk_1A;  // 2 loads, 0 stores
    u8 pad_1C[0x18];
    u32 unk_34;  // 1 loads, 0 stores
    u32 unk_38;  // 1 loads, 0 stores
    u8 pad_3C[0xAC];
    u8 unk_E8;  // 7 loads, 0 stores
} Obj_1_bss_6C84C_Target;
extern Obj_1_bss_6C84C_Target *lbl_1_bss_6C84C;

// lbl_1_data_1D2EC: .data size 0x228, 1 refs from avline.c (own data block)
extern u8 lbl_1_data_1D2EC[0x228];

#endif  // REL_MAIN_REL_AVLINE_H
