#ifndef REL_MAIN_REL_BG_AUR_H
#define REL_MAIN_REL_BG_AUR_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu bg_aur.c`: globals of bg_aur.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_bss_8ED88: .bss size 0x2, 2 refs from bg_aur.c
extern u32 lbl_1_bss_8ED88;

// lbl_1_data_463C8: .data size 0x40, 1 refs from bg_aur.c (own data block)
extern u8 lbl_1_data_463C8[0x40];

#endif  // REL_MAIN_REL_BG_AUR_H
