#ifndef REL_MAIN_REL_BG_COMMON_H
#define REL_MAIN_REL_BG_COMMON_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu bg_common.c`: globals of bg_common.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_bss_85290: .bss size 0x4, 4 refs from bg_common.c
extern f32 lbl_1_bss_85290;

// lbl_1_bss_854B8: .bss size 0x1A08, 3 refs from bg_common.c
typedef struct {
    u8 pad_0[0x8];
    u32 unk_8;  // 1 loads, 0 stores
    u8 pad_C[0x28];
    u32 unk_34;  // 4 loads, 0 stores
} Obj_1_bss_854B8_At4;
typedef struct {
    u32 unk_0;  // 2 loads, 1 stores
    u8 pad_4[0x14];
    u16 unk_18;  // 0 loads, 3 stores
} Obj_1_bss_854B8_At8;
typedef struct {
    u32 unk_0;  // 1 loads, 2 stores
    Obj_1_bss_854B8_At4 *unk_4;  // 2 loads, 2 stores
    Obj_1_bss_854B8_At8 *unk_8;  // 1 loads, 2 stores
    s16 unk_C;  // 1 loads, 1 stores
    u8 pad_E[0x19FA];
} Obj_1_bss_854B8;
extern Obj_1_bss_854B8 lbl_1_bss_854B8;

// lbl_1_data_3F510: .data size 0x68, 3 refs from bg_common.c (own data block)
extern u8 lbl_1_data_3F510[0x68];

// lbl_1_bss_86ED0: .bss size 0x1C70, 3 refs from bg_common.c
typedef struct {
    u8 pad_0[0x8];
    u32 unk_8;  // 7 loads, 0 stores
    u32 unk_C;  // 4 loads, 0 stores
    u32 unk_10;  // 3 loads, 0 stores
    u8 pad_14[0x1C5C];
} Obj_1_bss_86ED0;
extern Obj_1_bss_86ED0 lbl_1_bss_86ED0;

// lbl_1_bss_86EC0: .bss size 0x4, 3 refs from bg_common.c
extern u32 lbl_1_bss_86EC0;

// lbl_1_bss_85280: .bss size 0x8, 3 refs from bg_common.c
typedef struct {
    u32 unk_0;  // 3 loads, 2 stores
    u32 unk_4;  // 5 loads, 2 stores
} Obj_1_bss_85280;
extern Obj_1_bss_85280 lbl_1_bss_85280;

// lbl_1_data_3FCAC: .data size 0x310, 3 refs from bg_common.c (own data block)
extern u8 lbl_1_data_3FCAC[0x310];

// lbl_1_data_3F34C: .data size 0xC, 2 refs from bg_common.c (own data block)
extern u8 lbl_1_data_3F34C[0xC];

// lbl_1_data_3F428: .data size 0xE8, 1 refs from bg_common.c (own data block)
typedef struct {
    u16 unk_0;  // 0 loads, 1 stores
    u8 pad_2[0xE6];
} Obj_1_data_3F428;
extern Obj_1_data_3F428 lbl_1_data_3F428;

// lbl_1_data_3F358: .data size 0xB0, 1 refs from bg_common.c (own data block)
extern u8 lbl_1_data_3F358[0xB0];

// lbl_1_data_3F9E0: .data size 0xF, 1 refs from bg_common.c (own data block)
extern u8 lbl_1_data_3F9E0[0xF];

// jumptable_1_data_3F408: .data size 0x1C, 1 refs from bg_common.c (own data block)
extern u8 jumptable_1_data_3F408[0x1C];

// lbl_1_data_3F9CC: .data size 0x13, 1 refs from bg_common.c (own data block)
extern u8 lbl_1_data_3F9CC[0x13];

#endif  // REL_MAIN_REL_BG_COMMON_H
