#ifndef REL_MAIN_REL_BG_FOR_H
#define REL_MAIN_REL_BG_FOR_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu bg_for.c`: globals of bg_for.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_data_3DDA8: .data size 0xC, 3 refs from bg_for.c (own data block)
extern u8 lbl_1_data_3DDA8[0xC];

// lbl_1_bss_38454: .bss size 0x4, 3 refs from bg_for.c
typedef struct {
    u8 pad_0[0x8];
    u32 unk_8;  // 15 loads, 0 stores
} Obj_1_bss_38454_Target;
extern Obj_1_bss_38454_Target *lbl_1_bss_38454;

// lbl_1_bss_7AE88: .bss size 0x30, 2 refs from bg_for.c
typedef struct {
    u8 pad_0[0x554];
    f32 unk_554;  // 1 loads, 0 stores
    u8 pad_558[0x24];
    f32 unk_57C;  // 1 loads, 0 stores
    u8 pad_580[0x6C];
    f32 unk_5EC;  // 1 loads, 0 stores
    u8 pad_5F0[0x14EC];
    f32 unk_1ADC;  // 1 loads, 0 stores
    u8 pad_1AE0[0x24];
    f32 unk_1B04;  // 1 loads, 0 stores
    u8 pad_1B08[0x6C];
    f32 unk_1B74;  // 1 loads, 0 stores
    u8 pad_1B78[0xAFC];
    f32 unk_2674;  // 1 loads, 0 stores
    u8 pad_2678[0x24];
    f32 unk_269C;  // 1 loads, 0 stores
    u8 pad_26A0[0x6C];
    f32 unk_270C;  // 1 loads, 0 stores
    u8 pad_2710[0x508C];
    f32 unk_779C;  // 2 loads, 0 stores
    u8 pad_77A0[0x24];
    f32 unk_77C4;  // 2 loads, 0 stores
    u8 pad_77C8[0x6C];
    f32 unk_7834;  // 2 loads, 0 stores
} Obj_1_bss_7AE88_At10;
typedef struct {
    u32 unk_0;  // 13 loads, 3 stores
    s16 unk_4;  // 12 loads, 3 stores
    u8 pad_6[0x2];
    u32 unk_8;  // 12 loads, 3 stores
    s16 unk_C;  // 11 loads, 5 stores
    u8 pad_E[0x2];
    Obj_1_bss_7AE88_At10 *unk_10;  // 20 loads, 3 stores
    s16 unk_14;  // 11 loads, 5 stores
    u8 pad_16[0x2];
    u32 unk_18;  // 12 loads, 3 stores
    s16 unk_1C;  // 11 loads, 3 stores
    u8 pad_1E[0x2];
    u32 unk_20;  // 12 loads, 3 stores
    s16 unk_24;  // 11 loads, 4 stores
    u8 pad_26[0x2];
    u32 unk_28;  // 12 loads, 3 stores
    s16 unk_2C;  // 12 loads, 5 stores
    u8 pad_2E[0x2];
} Obj_1_bss_7AE88;
extern Obj_1_bss_7AE88 lbl_1_bss_7AE88;

// lbl_1_data_2B0D4: .data size 0x70, 2 refs from bg_for.c
typedef struct {
    u8 pad_0[0xA];
    s16 unk_A;  // 1 loads, 0 stores
    u8 pad_C[0x64];
} Obj_1_data_2B0D4;
extern Obj_1_data_2B0D4 lbl_1_data_2B0D4;

// jumptable_1_data_3DCE0: .data size 0xC8, 1 refs from bg_for.c (own data block)
extern u8 jumptable_1_data_3DCE0[0xC8];

// lbl_1_data_3DC78: .data size 0x9, 1 refs from bg_for.c (own data block)
extern u8 lbl_1_data_3DC78[0x9];

// lbl_1_data_3DC84: .data size 0x11, 1 refs from bg_for.c (own data block)
typedef struct {
    u32 unk_0;  // 17 loads, 3 stores
    u32 unk_4;  // 0 loads, 3 stores
    u8 pad_8[0x4];
    u32 unk_C;  // 8 loads, 8 stores
    u8 pad_10[0x1];
} Obj_1_data_3DC84;
extern Obj_1_data_3DC84 lbl_1_data_3DC84;

#endif  // REL_MAIN_REL_BG_FOR_H
