#ifndef REL_MAIN_REL_BG_LIG_H
#define REL_MAIN_REL_BG_LIG_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu bg_lig.c`: globals of bg_lig.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_bss_7AD78: .bss size 0x40, 3 refs from bg_lig.c
typedef struct {
    u8 pad_0[0x14];
    u32 unk_14;  // 1 loads, 0 stores
    u8 pad_18[0x1C];
    u32 unk_34;  // 1 loads, 0 stores
    u8 pad_38[0x8];
} Obj_1_bss_7AD78;
extern Obj_1_bss_7AD78 lbl_1_bss_7AD78;

// jumptable_1_data_3DC08: .data size 0x2C, 1 refs from bg_lig.c (own data block)
extern u8 jumptable_1_data_3DC08[0x2C];

// lbl_1_data_3DBE8: .data size 0x9, 1 refs from bg_lig.c (own data block)
extern u8 lbl_1_data_3DBE8[0x9];

// lbl_1_data_3DBF4: .data size 0x11, 1 refs from bg_lig.c (own data block)
extern u8 lbl_1_data_3DBF4[0x11];

// lbl_1_data_3DC38: .data size 0x18, 1 refs from bg_lig.c (own data block)
extern u8 lbl_1_data_3DC38[0x18];

#endif  // REL_MAIN_REL_BG_LIG_H
