#ifndef REL_MAIN_REL_BG_SAN_H
#define REL_MAIN_REL_BG_SAN_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu bg_san.c`: globals of bg_san.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_data_3DC50: .data size 0x9, 3 refs from bg_san.c (own data block)
extern u8 lbl_1_data_3DC50[0x9];

// lbl_1_data_3DC70: .data size 0x8, 1 refs from bg_san.c (own data block)
extern u32 lbl_1_data_3DC70;

// lbl_1_data_3DC5C: .data size 0x11, 1 refs from bg_san.c (own data block)
extern u8 lbl_1_data_3DC5C[0x11];

#endif  // REL_MAIN_REL_BG_SAN_H
