#ifndef REL_MAIN_REL_BG_TOW_H
#define REL_MAIN_REL_BG_TOW_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu bg_tow.c`: globals of bg_tow.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_data_49AB4: .data size 0x14, 4 refs from bg_tow.c (own data block)
typedef struct {
    u32 unk_0;  // 1 loads, 8 stores
    u8 pad_4[0x10];
} Obj_1_data_49AB4;
extern Obj_1_data_49AB4 lbl_1_data_49AB4;

// lbl_1_bss_8ED90: .bss size 0x4, 3 refs from bg_tow.c
extern u32 lbl_1_bss_8ED90;

// lbl_1_data_49A18: .data size 0x14, 3 refs from bg_tow.c (own data block)
extern u8 lbl_1_data_49A18[0x14];

// lbl_1_bss_8EDA4: .bss size 0x4C, 2 refs from bg_tow.c
typedef struct {
    u32 unk_0;  // 0 loads, 1 stores
    u8 unk_4;  // 0 loads, 2 stores
    u8 pad_5[0x47];
} Obj_1_bss_8EDA4;
extern Obj_1_bss_8EDA4 lbl_1_bss_8EDA4;

// lbl_1_data_49AB0: .data size 0x4, 1 refs from bg_tow.c (own data block)
extern u32 lbl_1_data_49AB0;

// lbl_1_data_46408: .data size 0x60, 1 refs from bg_tow.c (own data block)
extern u8 lbl_1_data_46408[0x60];

#endif  // REL_MAIN_REL_BG_TOW_H
