#ifndef REL_MAIN_REL_BITMAP_H
#define REL_MAIN_REL_BITMAP_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu bitmap.c`: globals of bitmap.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_data_FCD4: .data size 0x1D60, 11 refs from bitmap.c
typedef struct {
    u32 unk_0;  // 1 loads, 0 stores
    u8 pad_4[0x20];
    u8 unk_24;  // 4 loads, 0 stores
    u8 pad_25[0x3];
    u32 unk_28;  // 6 loads, 0 stores
    u8 pad_2C[0x20];
    u8 unk_4C;  // 3 loads, 0 stores
    u8 pad_4D[0x1D13];
} Obj_1_data_FCD4;
extern Obj_1_data_FCD4 lbl_1_data_FCD4;

// lbl_1_data_1A368: .data size 0x9, 7 refs from bitmap.c (own data block)
extern u8 lbl_1_data_1A368[0x9];

// lbl_1_data_1A374: .data size 0x19, 4 refs from bitmap.c (own data block)
extern u8 lbl_1_data_1A374[0x19];

// lbl_1_data_6CA0: .data size 0x24, 3 refs from bitmap.c
extern u8 lbl_1_data_6CA0[0x24];

// lbl_1_bss_3E058: .bss size 0x4, 2 refs from bitmap.c
extern u32 lbl_1_bss_3E058;

// lbl_1_data_1AEA8: .data size 0x9A0, 2 refs from bitmap.c (own data block)
typedef struct {
    u32 unk_0;  // 2 loads, 0 stores
    u8 pad_4[0x28];
    u32 unk_2C;  // 4 loads, 0 stores
    u32 unk_30;  // 4 loads, 0 stores
    u8 pad_34[0x4];
    u32 unk_38;  // 3 loads, 0 stores
    u8 pad_3C[0x2C];
    u32 unk_68;  // 1 loads, 0 stores
    u8 pad_6C[0x8F0];
    u32 unk_95C;  // 1 loads, 0 stores
    u8 pad_960[0x40];
} Obj_1_data_1AEA8;
extern Obj_1_data_1AEA8 lbl_1_data_1AEA8;

// lbl_1_data_1A3B8: .data size 0xAD8, 2 refs from bitmap.c (own data block)
typedef struct {
    u16 unk_0;  // 2 loads, 0 stores
    u8 pad_2[0xAD6];
} Obj_1_data_1A3B8;
extern Obj_1_data_1A3B8 lbl_1_data_1A3B8;

// lbl_1_data_1BCC4: .data size 0x4, 2 refs from bitmap.c (own data block)
extern u32 lbl_1_data_1BCC4;

// lbl_1_data_1A390: .data size 0x1A, 1 refs from bitmap.c (own data block)
extern u8 lbl_1_data_1A390[0x1A];

#endif  // REL_MAIN_REL_BITMAP_H
