#ifndef REL_MAIN_REL_BURNER_H
#define REL_MAIN_REL_BURNER_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu burner.c`: globals of burner.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_data_2A0C0: .data size 0x10, 10 refs from burner.c (own data block)
extern u8 lbl_1_data_2A0C0[0x10];

// lbl_1_bss_6EA04: .bss size 0x4, 9 refs from burner.c
typedef struct {
    u32 unk_0;  // 0 loads, 1 stores
    u32 unk_4;  // 7 loads, 2 stores
    u8 pad_8[0x4A4];
} Obj_1_bss_6EA04_Target;
extern Obj_1_bss_6EA04_Target *lbl_1_bss_6EA04;  // array of 0x4AC-byte records

// lbl_1_data_27DE0: .data size 0x28, 5 refs from burner.c
typedef struct {
    u8 pad_0[0x4];
    u32 unk_4;  // 2 loads, 0 stores
    u32 unk_8;  // 1 loads, 0 stores
    u32 unk_C;  // 1 loads, 0 stores
    u8 pad_10[0x18];
} Obj_1_data_27DE0;
extern Obj_1_data_27DE0 lbl_1_data_27DE0;

// lbl_1_data_2B0D4: .data size 0x70, 4 refs from burner.c (own data block)
typedef struct {
    u8 pad_0[0xA];
    s16 unk_A;  // 1 loads, 0 stores
    u8 pad_C[0x64];
} Obj_1_data_2B0D4;
extern Obj_1_data_2B0D4 lbl_1_data_2B0D4;

// lbl_1_bss_384B4: .bss size 0x4, 4 refs from burner.c
extern u32 lbl_1_bss_384B4;

// lbl_1_bss_6EA00: .bss size 0x4, 3 refs from burner.c
extern f32 lbl_1_bss_6EA00;

// lbl_1_bss_6EA08: .bss size 0x4, 3 refs from burner.c
extern u32 lbl_1_bss_6EA08;

// lbl_1_bss_384B8: .bss size 0x8, 3 refs from burner.c
extern u32 lbl_1_bss_384B8;

// lbl_1_data_2B144: .data size 0x18, 2 refs from burner.c (own data block)
extern u8 lbl_1_data_2B144[0x18];

// lbl_1_data_27E08: .data size 0x9, 2 refs from burner.c (own data block)
extern u8 lbl_1_data_27E08[0x9];

// lbl_1_data_2A8D8: .data size 0x54, 2 refs from burner.c (own data block)
extern u8 lbl_1_data_2A8D8[0x54];

// lbl_1_bss_84: .bss size 0x18, 2 refs from burner.c
typedef struct {
    u32 unk_0;  // 5 loads, 0 stores
} Obj_1_bss_84_At0;
typedef struct {
    Obj_1_bss_84_At0 *unk_0;  // 6 loads, 0 stores
    u32 unk_4;  // 1 loads, 0 stores
    u32 unk_8;  // 1 loads, 0 stores
    u32 unk_C;  // 1 loads, 0 stores
    u32 unk_10;  // 2 loads, 0 stores
    u32 unk_14;  // 2 loads, 2 stores
} Obj_1_bss_84;
extern Obj_1_bss_84 lbl_1_bss_84;

// lbl_1_data_28060: .data size 0x2060, 2 refs from burner.c (own data block)
typedef struct {
    u8 pad_0[0x4];
    f32 unk_4;  // 2 loads, 0 stores
    u8 pad_8[0x2058];
} Obj_1_data_28060;
extern Obj_1_data_28060 lbl_1_data_28060;

// lbl_1_data_2A92C: .data size 0x54, 1 refs from burner.c (own data block)
extern u8 lbl_1_data_2A92C[0x54];

// lbl_1_data_2AB54: .data size 0x58, 1 refs from burner.c (own data block)
extern u8 lbl_1_data_2AB54[0x58];

// lbl_1_data_2AA24: .data size 0x58, 1 refs from burner.c (own data block)
extern u8 lbl_1_data_2AA24[0x58];

// lbl_1_data_2BD54: .data size 0xA68, 1 refs from burner.c (own data block)
extern u8 lbl_1_data_2BD54[0xA68];

// lbl_1_data_2ABAC: .data size 0x318, 1 refs from burner.c (own data block)
typedef struct {
    u8 pad_0[0x8];
    u32 unk_8;  // 1 loads, 0 stores
    u8 pad_C[0x30C];
} Obj_1_data_2ABAC;
extern Obj_1_data_2ABAC lbl_1_data_2ABAC;

#endif  // REL_MAIN_REL_BURNER_H
