#ifndef REL_MAIN_REL_CAR_H
#define REL_MAIN_REL_CAR_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu car.c`: globals of car.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_data_1F1D8: .data size 0x8, 15 refs from car.c
extern u32 lbl_1_data_1F1D8;

// lbl_1_data_209C0: .data size 0x8, 11 refs from car.c (own data block)
extern u32 lbl_1_data_209C0;

// lbl_1_data_1FFF0: .data size 0xC, 10 refs from car.c (own data block)
extern u8 lbl_1_data_1FFF0[0xC];

// lbl_1_bss_6D83C: .bss size 0xE, 8 refs from car.c
typedef struct {
    u32 unk_0;  // 8 loads, 0 stores
    u8 pad_4[0xA];
} Obj_1_bss_6D83C;
extern Obj_1_bss_6D83C lbl_1_bss_6D83C;

// lbl_1_bss_6D84A: .bss size 0x6, 8 refs from car.c
extern u8 lbl_1_bss_6D84A;

// lbl_1_bss_6D82C: .bss size 0xC, 6 refs from car.c
typedef struct {
    u32 unk_0;  // 13 loads, 10 stores
    u8 pad_4[0x8];
} Obj_1_bss_6D82C;
extern Obj_1_bss_6D82C lbl_1_bss_6D82C;

// lbl_1_bss_6E960: .bss size 0x18, 3 refs from car.c
typedef struct {
    u32 unk_0;  // 30 loads, 7 stores
    u32 unk_4;  // 15 loads, 3 stores
    u32 unk_8;  // 6 loads, 3 stores
    u32 unk_C;  // 6 loads, 3 stores
    u32 unk_10;  // 6 loads, 3 stores
    u32 unk_14;  // 8 loads, 3 stores
} Obj_1_bss_6E960;
extern Obj_1_bss_6E960 lbl_1_bss_6E960;

// lbl_1_bss_D58: .bss size 0x18, 3 refs from car.c
typedef struct {
    u16 unk_0;  // 4 loads, 0 stores
    u16 unk_2;  // 1 loads, 0 stores
    u8 pad_4[0x4];
    u16 unk_8;  // 24 loads, 0 stores
    u16 unk_A;  // 3 loads, 0 stores
    u8 pad_C[0x4];
    u16 unk_10;  // 18 loads, 0 stores
    u16 unk_12;  // 4 loads, 0 stores
    u8 pad_14[0x4];
} Obj_1_bss_D58;
extern Obj_1_bss_D58 lbl_1_bss_D58;

// lbl_1_bss_6E958: .bss size 0x8, 3 refs from car.c
typedef struct {
    u32 unk_0;  // 3 loads, 2 stores
    u32 unk_4;  // 3 loads, 2 stores
} Obj_1_bss_6E958;
extern Obj_1_bss_6E958 lbl_1_bss_6E958;

// lbl_1_data_27BA4: .data size 0x5C, 3 refs from car.c (own data block)
extern u8 lbl_1_data_27BA4[0x5C];

// lbl_1_data_278AC: .data size 0x3, 3 refs from car.c (own data block)
extern u32 lbl_1_data_278AC;

// lbl_1_data_20700: .data size 0x11, 2 refs from car.c (own data block)
extern u8 lbl_1_data_20700[0x11];

// lbl_1_bss_6D868: .bss size 0x1, 2 refs from car.c
extern u8 lbl_1_bss_6D868;

// lbl_1_data_2065C: .data size 0x1, 2 refs from car.c (own data block)
extern u8 lbl_1_data_2065C;

// lbl_1_bss_6D824: .bss size 0x4, 2 refs from car.c
extern u32 lbl_1_bss_6D824;

// lbl_1_bss_C70: .bss size 0x50, 2 refs from car.c
typedef struct {
    u8 pad_0[0x4];
    f32 unk_4;  // 1 loads, 0 stores
    f32 unk_8;  // 4 loads, 0 stores
    f32 unk_C;  // 1 loads, 0 stores
    f32 unk_10;  // 1 loads, 0 stores
    u8 pad_14[0x3C];
} Obj_1_bss_C70;
extern Obj_1_bss_C70 lbl_1_bss_C70;

// lbl_1_bss_A88: .bss size 0x18, 2 refs from car.c
typedef struct {
    u8 unk_0;  // 1 loads, 0 stores
    u8 pad_1[0x17];
} Obj_1_bss_A88;
extern Obj_1_bss_A88 lbl_1_bss_A88;

// lbl_1_bss_525C: .bss size 0x198, 2 refs from car.c
typedef struct {
    u32 unk_0;  // 1 loads, 0 stores
    u8 pad_4[0x1];
    u8 unk_5;  // 1 loads, 0 stores
    u8 pad_6[0x1];
    u8 unk_7;  // 1 loads, 0 stores
    u8 pad_8[0xF0];
    u8 unk_F8;  // 2 loads, 0 stores
    u8 pad_F9[0x98];
    u8 unk_191;  // 2 loads, 0 stores
    u8 unk_192;  // 2 loads, 0 stores
    u8 pad_193[0x5];
} Obj_1_bss_525C;
extern Obj_1_bss_525C lbl_1_bss_525C;

// lbl_1_bss_6D9A0: .bss size 0xBC, 2 refs from car.c
extern u8 lbl_1_bss_6D9A0[0xBC];

// lbl_1_bss_6D864: .bss size 0x4, 2 refs from car.c
extern u32 lbl_1_bss_6D864;

// lbl_1_data_27920: .data size 0x4, 1 refs from car.c (own data block)
extern u32 lbl_1_data_27920;

// lbl_1_data_27924: .data size 0x108, 1 refs from car.c (own data block)
typedef struct {
    u32 unk_0;  // 0 loads, 1 stores
    u8 pad_4[0x104];
} Obj_1_data_27924;
extern Obj_1_data_27924 lbl_1_data_27924;

// lbl_1_data_22A24: .data size 0x5, 1 refs from car.c (own data block)
extern u32 lbl_1_data_22A24;

// lbl_1_data_22A1C: .data size 0x5, 1 refs from car.c (own data block)
extern u32 lbl_1_data_22A1C;

// lbl_1_data_24EF0: .data size 0x7, 1 refs from car.c (own data block)
extern u32 lbl_1_data_24EF0;

// lbl_1_data_2090C: .data size 0x88, 1 refs from car.c (own data block)
extern u8 lbl_1_data_2090C[0x88];

// jumptable_1_data_207F0: .data size 0xA4, 1 refs from car.c (own data block)
extern u8 jumptable_1_data_207F0[0xA4];

// lbl_1_data_26B60: .data size 0xB4, 1 refs from car.c (own data block)
extern u8 lbl_1_data_26B60[0xB4];

// lbl_1_data_26C14: .data size 0x13C, 1 refs from car.c (own data block)
extern u8 lbl_1_data_26C14[0x13C];

// lbl_1_data_20D1C: .data size 0xB4, 1 refs from car.c (own data block)
extern u8 lbl_1_data_20D1C[0xB4];

// lbl_1_data_2057C: .data size 0x16, 1 refs from car.c (own data block)
extern u8 lbl_1_data_2057C[0x16];

// lbl_1_data_20714: .data size 0xA, 1 refs from car.c (own data block)
extern u8 lbl_1_data_20714[0xA];

// lbl_1_data_278B0: .data size 0x70, 1 refs from car.c (own data block)
extern u8 lbl_1_data_278B0[0x70];

// lbl_1_data_20660: .data size 0x1, 1 refs from car.c (own data block)
extern u8 lbl_1_data_20660;

// lbl_1_data_20994: .data size 0x12, 1 refs from car.c (own data block)
extern u8 lbl_1_data_20994[0x12];

// lbl_1_data_209A8: .data size 0x12, 1 refs from car.c (own data block)
extern u8 lbl_1_data_209A8[0x12];

// lbl_1_data_20664: .data size 0x74, 1 refs from car.c (own data block)
typedef struct {
    u8 unk_0;  // 2 loads, 0 stores
    u8 unk_1;  // 2 loads, 0 stores
    u8 pad_2[0x72];
} Obj_1_data_20664;
extern Obj_1_data_20664 lbl_1_data_20664;

// lbl_1_data_208A8: .data size 0x64, 1 refs from car.c (own data block)
extern u8 lbl_1_data_208A8[0x64];

// jumptable_1_data_27A2C: .data size 0x38, 1 refs from car.c (own data block)
extern u8 jumptable_1_data_27A2C[0x38];

// lbl_1_data_20594: .data size 0x12, 1 refs from car.c (own data block)
extern u8 lbl_1_data_20594[0x12];

// lbl_1_data_205A8: .data size 0xB4, 1 refs from car.c (own data block)
extern u8 lbl_1_data_205A8[0xB4];

// lbl_1_data_206D8: .data size 0x28, 1 refs from car.c (own data block)
extern u8 lbl_1_data_206D8[0x28];

// lbl_1_data_2785C: .data size 0x10, 1 refs from car.c (own data block)
extern u8 lbl_1_data_2785C[0x10];

// lbl_1_data_27870: .data size 0x4, 1 refs from car.c (own data block)
extern u32 lbl_1_data_27870;

// lbl_1_data_27874: .data size 0x38, 1 refs from car.c (own data block)
extern u8 lbl_1_data_27874[0x38];

// lbl_1_data_2786C: .data size 0x4, 1 refs from car.c (own data block)
extern u32 lbl_1_data_2786C;

#endif  // REL_MAIN_REL_CAR_H
