#ifndef REL_MAIN_REL_DRIVER_H
#define REL_MAIN_REL_DRIVER_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu driver.c`: globals of driver.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_bss_6F648: .bss size 0x1010, 7 refs from driver.c
typedef struct {
    u8 unk_0;  // 3 loads, 1 stores
    u8 unk_1;  // 0 loads, 1 stores
    u8 unk_2;  // 4 loads, 2 stores
    u8 pad_3[0x1];
    u16 unk_4;  // 1 loads, 2 stores
    s16 unk_6;  // 1 loads, 3 stores
    s16 unk_8;  // 2 loads, 4 stores
    u8 pad_A[0x2];
    u32 unk_C;  // 6 loads, 6 stores
    u8 pad_10[0x1000];
} Obj_1_bss_6F648;
extern Obj_1_bss_6F648 lbl_1_bss_6F648;

// lbl_1_bss_71690: .bss size 0x30, 7 refs from driver.c
typedef struct {
    u32 unk_0;  // 9 loads, 2 stores
    f32 unk_4;  // 1 loads, 0 stores
    f32 unk_8;  // 1 loads, 0 stores
    f32 unk_C;  // 1 loads, 0 stores
    f32 unk_10;  // 1 loads, 0 stores
    u8 pad_14[0x1C];
} Obj_1_bss_71690;
extern Obj_1_bss_71690 lbl_1_bss_71690;

// lbl_1_data_34348: .data size 0xC, 4 refs from driver.c
typedef struct {
    u8 unk_0;  // 2 loads, 0 stores
    u8 unk_1;  // 1 loads, 0 stores
    u8 unk_2;  // 1 loads, 0 stores
    u8 unk_3;  // 1 loads, 0 stores
    u8 unk_4;  // 1 loads, 0 stores
    u8 unk_5;  // 1 loads, 0 stores
    u8 unk_6;  // 1 loads, 0 stores
    u8 unk_7;  // 1 loads, 0 stores
    u8 unk_8;  // 1 loads, 0 stores
    u8 unk_9;  // 1 loads, 0 stores
    u8 pad_A[0x2];
} Obj_1_data_34348;
extern Obj_1_data_34348 lbl_1_data_34348;

// lbl_1_bss_716C0: .bss size 0x8, 4 refs from driver.c
extern u8 lbl_1_bss_716C0[8];

// lbl_1_data_34354: .data size 0x48, 4 refs from driver.c (own data block)
extern u8 lbl_1_data_34354[0x48];

// lbl_1_bss_6F638: .bss size 0x8, 4 refs from driver.c
extern u32 lbl_1_bss_6F638[2];

// lbl_1_bss_6F640: .bss size 0x8, 3 refs from driver.c
extern u32 lbl_1_bss_6F640[2];

// lbl_1_bss_71674: .bss size 0x8, 2 refs from driver.c
extern u32 lbl_1_bss_71674[2];

// lbl_1_data_35990: .data size 0xC, 2 refs from driver.c (own data block)
extern u8 lbl_1_data_35990[0xC];

// lbl_1_data_3599C: .data size 0x3C, 2 refs from driver.c (own data block)
typedef struct {
    u32 unk_0;  // 0 loads, 2 stores
    u8 pad_4[0x38];
} Obj_1_data_3599C;
extern Obj_1_data_3599C lbl_1_data_3599C;

// lbl_1_data_20D1C: .data size 0xB4, 2 refs from driver.c
extern u8 lbl_1_data_20D1C[0xB4];

// lbl_1_data_35864: .data size 0x12C, 2 refs from driver.c (own data block)
extern u8 lbl_1_data_35864[0x12C];

// lbl_1_data_35A70: .data size 0x48, 1 refs from driver.c (own data block)
extern u8 lbl_1_data_35A70[0x48];

// lbl_1_data_35AB8: .data size 0xB, 1 refs from driver.c (own data block)
extern u8 lbl_1_data_35AB8[0xB];

// jumptable_1_data_3439C: .data size 0x28, 1 refs from driver.c (own data block)
extern u8 jumptable_1_data_3439C[0x28];

// lbl_1_data_35654: .data size 0x210, 1 refs from driver.c (own data block)
extern u8 lbl_1_data_35654[0x210];

// lbl_1_data_355A4: .data size 0xB0, 1 refs from driver.c (own data block)
extern u8 lbl_1_data_355A4[0xB0];

// lbl_1_data_3C1E4: .data size 0x4, 1 refs from driver.c (own data block)
extern u32 lbl_1_data_3C1E4;

// lbl_1_data_343C4: .data size 0x210, 1 refs from driver.c (own data block)
typedef struct {
    u32 unk_0;  // 1 loads, 0 stores
    u32 unk_4;  // 1 loads, 0 stores
    u32 unk_8;  // 1 loads, 0 stores
    u8 pad_C[0x204];
} Obj_1_data_343C4;
extern Obj_1_data_343C4 lbl_1_data_343C4;

// lbl_1_data_345D4: .data size 0xFD0, 1 refs from driver.c (own data block)
typedef struct {
    u8 pad_0[0x48];
    f32 unk_48;  // 2 loads, 0 stores
    f32 unk_4C;  // 2 loads, 0 stores
    f32 unk_50;  // 2 loads, 0 stores
    f32 unk_54;  // 1 loads, 0 stores
    f32 unk_58;  // 1 loads, 0 stores
    u8 pad_5C[0xF74];
} Obj_1_data_345D4;
extern Obj_1_data_345D4 lbl_1_data_345D4;

// lbl_1_data_3B74C: .data size 0xA98, 1 refs from driver.c (own data block)
typedef struct {
    u32 unk_0;  // 4 loads, 0 stores
    u8 pad_4[0xA94];
} Obj_1_data_3B74C;
extern Obj_1_data_3B74C lbl_1_data_3B74C;

#endif  // REL_MAIN_REL_DRIVER_H
