#ifndef REL_MAIN_REL_ENEMY_CTRL_H
#define REL_MAIN_REL_ENEMY_CTRL_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu enemy_ctrl.c`: globals of enemy_ctrl.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_data_3D648: .data size 0x28, 17 refs from enemy_ctrl.c (own data block)
typedef struct {
    u32 unk_0;  // 1 loads, 0 stores
    u16 unk_4;  // 5 loads, 0 stores
    u16 unk_6;  // 5 loads, 0 stores
    u16 unk_8;  // 0 loads, 1 stores
    u8 pad_A[0x6];
    u16 unk_10;  // 1 loads, 0 stores
    u16 unk_12;  // 1 loads, 0 stores
    u16 unk_14;  // 1 loads, 0 stores
    u16 unk_16;  // 1 loads, 0 stores
    u16 unk_18;  // 1 loads, 0 stores
    u8 pad_1A[0x2];
    u32 unk_1C;  // 1 loads, 0 stores
    u8 unk_20;  // 0 loads, 1 stores
    u8 unk_21;  // 0 loads, 1 stores
    u8 unk_22;  // 0 loads, 1 stores
    u8 unk_23;  // 0 loads, 1 stores
    u8 pad_24[0x4];
} Obj_1_data_3D648;
extern Obj_1_data_3D648 lbl_1_data_3D648;

// lbl_1_bss_7ACA0: .bss size 0x30, 6 refs from enemy_ctrl.c
extern u8 lbl_1_bss_7ACA0[0x30];

// lbl_1_data_3D570: .data size 0x4, 3 refs from enemy_ctrl.c (own data block)
extern u32 lbl_1_data_3D570;

// lbl_1_bss_4E6A8: .bss size 0x4, 3 refs from enemy_ctrl.c
extern u32 lbl_1_bss_4E6A8;

// lbl_1_bss_4E6AC: .bss size 0x4, 3 refs from enemy_ctrl.c
extern u32 lbl_1_bss_4E6AC;

// lbl_1_data_3D574: .data size 0x5, 2 refs from enemy_ctrl.c (own data block)
extern u32 lbl_1_data_3D574;

// lbl_1_data_3D290: .data size 0x4, 2 refs from enemy_ctrl.c (own data block)
extern u32 lbl_1_data_3D290;

// lbl_1_bss_84: .bss size 0x18, 2 refs from enemy_ctrl.c
typedef struct {
    u32 unk_0;  // 5 loads, 0 stores
} Obj_1_bss_84_At0;
typedef struct {
    Obj_1_bss_84_At0 *unk_0;  // 6 loads, 0 stores
    u32 unk_4;  // 1 loads, 0 stores
    u32 unk_8;  // 1 loads, 0 stores
    u32 unk_C;  // 1 loads, 0 stores
    u32 unk_10;  // 2 loads, 0 stores
    u32 unk_14;  // 2 loads, 2 stores
} Obj_1_bss_84;
extern Obj_1_bss_84 lbl_1_bss_84;

// lbl_1_data_3D670: .data size 0x4, 2 refs from enemy_ctrl.c (own data block)
extern u32 lbl_1_data_3D670;

// lbl_1_data_20D1C: .data size 0xB4, 2 refs from enemy_ctrl.c
extern u8 lbl_1_data_20D1C[0xB4];

// lbl_1_bss_9C: .bss size 0x1, 2 refs from enemy_ctrl.c
extern u8 lbl_1_bss_9C;

// lbl_1_data_3D928: .data size 0x104, 2 refs from enemy_ctrl.c (own data block)
typedef struct {
    u32 unk_0;  // 1 loads, 1 stores
    u8 pad_4[0x100];
} Obj_1_data_3D928;
extern Obj_1_data_3D928 lbl_1_data_3D928;

// lbl_1_data_3D57C: .data size 0x4, 2 refs from enemy_ctrl.c (own data block)
extern u32 lbl_1_data_3D57C;

// jumptable_1_data_3D580: .data size 0x30, 1 refs from enemy_ctrl.c (own data block)
extern u8 jumptable_1_data_3D580[0x30];

// lbl_1_data_3D634: .data size 0xF, 1 refs from enemy_ctrl.c (own data block)
extern u8 lbl_1_data_3D634[0xF];

// jumptable_1_data_3D5E0: .data size 0x50, 1 refs from enemy_ctrl.c (own data block)
extern u8 jumptable_1_data_3D5E0[0x50];

// lbl_1_data_3D554: .data size 0x4, 1 refs from enemy_ctrl.c (own data block)
extern f32 lbl_1_data_3D554;

// lbl_1_data_3D924: .data size 0x4, 1 refs from enemy_ctrl.c (own data block)
extern u32 lbl_1_data_3D924;

// lbl_1_data_3D558: .data size 0x18, 1 refs from enemy_ctrl.c (own data block)
typedef struct {
    f32 unk_0;  // 2 loads, 1 stores
    u8 pad_4[0x14];
} Obj_1_data_3D558;
extern Obj_1_data_3D558 lbl_1_data_3D558;

// lbl_1_data_3D234: .data size 0x38, 1 refs from enemy_ctrl.c (own data block)
extern u8 lbl_1_data_3D234[0x38];

// lbl_1_data_3D630: .data size 0x3, 1 refs from enemy_ctrl.c (own data block)
extern u32 lbl_1_data_3D630;

#endif  // REL_MAIN_REL_ENEMY_CTRL_H
