#ifndef REL_MAIN_REL_FACE_H
#define REL_MAIN_REL_FACE_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu face.c`: globals of face.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_data_3D924: .data size 0x4, 7 refs from face.c
extern u32 lbl_1_data_3D924;

// lbl_1_bss_7ACD8: .bss size 0x4, 7 refs from face.c
typedef struct {
    u32 unk_0;  // 8 loads, 8 stores
    u32 unk_4;  // 11 loads, 4 stores
    u32 unk_8;  // 0 loads, 3 stores
    u8 pad_C[0x4];
    u32 unk_10;  // 6 loads, 4 stores
    u32 unk_14;  // 7 loads, 4 stores
    u32 unk_18;  // 0 loads, 6 stores
    u32 unk_1C;  // 2 loads, 5 stores
    u8 pad_20[0xC];
    u32 unk_2C;  // 0 loads, 1 stores
    u32 unk_30;  // 0 loads, 1 stores
    u32 unk_34;  // 0 loads, 1 stores
    u32 unk_38;  // 3 loads, 5 stores
    u32 unk_3C;  // 1 loads, 8 stores
    u8 pad_40[0x20];
    u32 unk_60;  // 4 loads, 2 stores
} Obj_1_bss_7ACD8_Target;
extern Obj_1_bss_7ACD8_Target *lbl_1_bss_7ACD8;

// lbl_1_data_3DA2C: .data size 0xD4, 5 refs from face.c (own data block)
extern u8 lbl_1_data_3DA2C[0xD4];

// lbl_1_bss_7ACE5: .bss size 0x1, 3 refs from face.c
extern u8 lbl_1_bss_7ACE5;

// lbl_1_bss_7ACE8: .bss size 0x4, 2 refs from face.c
extern u32 lbl_1_bss_7ACE8;

// lbl_1_bss_7ACF0: .bss size 0x8, 2 refs from face.c
extern u32 lbl_1_bss_7ACF0;

// lbl_1_data_3DB2C: .data size 0x12, 1 refs from face.c (own data block)
extern u8 lbl_1_data_3DB2C[0x12];

// lbl_1_data_3DB40: .data size 0x18, 1 refs from face.c (own data block)
extern u8 lbl_1_data_3DB40[0x18];

// lbl_1_data_3DB00: .data size 0x2C, 1 refs from face.c (own data block)
extern u8 lbl_1_data_3DB00[0x2C];

// lbl_1_data_3DB58: .data size 0x33, 1 refs from face.c (own data block)
extern u8 lbl_1_data_3DB58[0x33];

// lbl_1_data_3DB8C: .data size 0x33, 1 refs from face.c (own data block)
extern u8 lbl_1_data_3DB8C[0x33];

#endif  // REL_MAIN_REL_FACE_H
