#ifndef REL_MAIN_REL_GHOST_H
#define REL_MAIN_REL_GHOST_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu ghost.c`: globals of ghost.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_data_3E358: .data size 0xC, 11 refs from ghost.c
extern u8 lbl_1_data_3E358[0xC];

// lbl_1_bss_7E9E8: .bss size 0x18, 5 refs from ghost.c
typedef struct {
    u32 unk_0;  // 3 loads, 2 stores
    u32 unk_4;  // 4 loads, 3 stores
    u32 unk_8;  // 4 loads, 3 stores
    u32 unk_C;  // 4 loads, 3 stores
    u8 pad_10[0x8];
} Obj_1_bss_7E9E8;
extern Obj_1_bss_7E9E8 lbl_1_bss_7E9E8;

// lbl_1_data_3E62C: .data size 0x80, 5 refs from ghost.c (own data block)
extern u8 lbl_1_data_3E62C[0x80];

// lbl_1_data_3E52C: .data size 0x4, 5 refs from ghost.c
extern u32 lbl_1_data_3E52C;

// lbl_1_bss_7ECB4: .bss size 0x48, 3 refs from ghost.c
typedef struct {
    u32 unk_0;  // 0 loads, 1 stores
    u8 unk_4;  // 0 loads, 1 stores
    u8 pad_5[0xF];
    u8 unk_14;  // 1 loads, 0 stores
    u8 pad_15[0x33];
} Obj_1_bss_7ECB4;
extern Obj_1_bss_7ECB4 lbl_1_bss_7ECB4;

// lbl_1_bss_77380: .bss size 0x3000, 2 refs from ghost.c
typedef struct {
    u32 unk_0;  // 2 loads, 2 stores
    u32 unk_4;  // 2 loads, 2 stores
    u32 unk_8;  // 2 loads, 2 stores
    u32 unk_C;  // 2 loads, 2 stores
    u32 unk_10;  // 2 loads, 2 stores
    u32 unk_14;  // 2 loads, 2 stores
    u32 unk_18;  // 2 loads, 2 stores
    u32 unk_1C;  // 2 loads, 2 stores
    u32 unk_20;  // 2 loads, 2 stores
    u32 unk_24;  // 4 loads, 2 stores
    u32 unk_28;  // 3 loads, 2 stores
    u32 unk_2C;  // 4 loads, 3 stores
    u8 pad_30[0x2FD0];
} Obj_1_bss_77380;
extern Obj_1_bss_77380 lbl_1_bss_77380;

// lbl_1_bss_7B1AC: .bss size 0x13D8, 2 refs from ghost.c
typedef struct {
    u8 pad_0[0x1];
    u8 unk_1;  // 1 loads, 0 stores
    u8 pad_2[0x13D6];
} Obj_1_bss_7B1AC;
extern Obj_1_bss_7B1AC lbl_1_bss_7B1AC;

// lbl_1_bss_7C584: .bss size 0x2C4, 2 refs from ghost.c
typedef struct {
    u32 unk_0;  // 1 loads, 1 stores
    u8 pad_4[0x2C0];
} Obj_1_bss_7C584;
extern Obj_1_bss_7C584 lbl_1_bss_7C584;

// lbl_1_bss_7B1A4: .bss size 0x8, 2 refs from ghost.c
extern u32 lbl_1_bss_7B1A4;

// lbl_1_bss_7ECFC: .bss size 0x5C, 2 refs from ghost.c
typedef struct {
    u32 unk_0;  // 1 loads, 2 stores
    u8 pad_4[0x58];
} Obj_1_bss_7ECFC;
extern Obj_1_bss_7ECFC lbl_1_bss_7ECFC;

// lbl_1_data_3E704: .data size 0x38, 1 refs from ghost.c (own data block)
extern u8 lbl_1_data_3E704[0x38];

// lbl_1_data_3E8A0: .data size 0x21, 1 refs from ghost.c (own data block)
extern u8 lbl_1_data_3E8A0[0x21];

// lbl_1_data_3E73C: .data size 0x158, 1 refs from ghost.c (own data block)
extern u8 lbl_1_data_3E73C[0x158];

// lbl_1_data_3E894: .data size 0x6, 1 refs from ghost.c (own data block)
extern u32 lbl_1_data_3E894;

// lbl_1_data_3E89C: .data size 0x4, 1 refs from ghost.c (own data block)
extern u32 lbl_1_data_3E89C;

// lbl_1_data_3E6AC: .data size 0x58, 1 refs from ghost.c (own data block)
extern u8 lbl_1_data_3E6AC[0x58];

#endif  // REL_MAIN_REL_GHOST_H
