#ifndef REL_MAIN_REL_GLOBALS_H
#define REL_MAIN_REL_GLOBALS_H

#include "types.h"

// Generated by `fzgx headers --module main_rel`: layouts recovered from every access in the
// module's disassembly (matched or not). Field names are offsets until the librarian names them;
// offsets and widths are facts, names are not. Regenerate rather than hand-edit padding.

// lbl_1_bss_960: .bss size 0x2, referenced by 110 functions, shape {'object': 231}
extern u16 lbl_1_bss_960;

// lbl_1_data_2A7E0: .data size 0xF8, referenced by 99 functions, shape {'object': 158}
// object reached through lbl_1_data_2A7E0.unk_3C
typedef struct {
    u32 unk_0;  // 26 loads, 15 stores
    u32 unk_4;  // 4 loads, 5 stores
    u32 unk_8;  // 4 loads, 5 stores
    u32 unk_C;  // 0 loads, 2 stores
    u32 unk_10;  // 9 loads, 4 stores
    u32 unk_14;  // 0 loads, 2 stores
    u32 unk_18;  // 0 loads, 2 stores
    u32 unk_1C;  // 0 loads, 2 stores
    u32 unk_20;  // 0 loads, 2 stores
    u32 unk_24;  // 0 loads, 2 stores
    u32 unk_28;  // 0 loads, 2 stores
    u32 unk_2C;  // 0 loads, 2 stores
    f32 unk_30;  // 0 loads, 3 stores
    f32 unk_34;  // 0 loads, 3 stores
    f32 unk_38;  // 0 loads, 3 stores
    f32 unk_3C;  // 0 loads, 3 stores
    f32 unk_40;  // 0 loads, 1 stores
    f32 unk_44;  // 0 loads, 1 stores
    f32 unk_48;  // 0 loads, 1 stores
    f32 unk_4C;  // 0 loads, 2 stores
    f32 unk_50;  // 0 loads, 2 stores
    f32 unk_54;  // 0 loads, 2 stores
    u32 unk_58;  // 0 loads, 2 stores
    /* overlap at 0x5A */
    u16 unk_5A;  // 0 loads, 1 stores
    u16 unk_5C;  // 4 loads, 3 stores
    /* overlap at 0x5D */
    u8 unk_5D;  // 13 loads, 6 stores
    u8 unk_5E;  // 4 loads, 2 stores
    u8 pad_5F[0x25];
    u32 unk_84;  // 22 loads, 5 stores
    u8 pad_88[0x8C];
    u32 unk_114;  // 0 loads, 1 stores
    u32 unk_118;  // 0 loads, 1 stores
    u32 unk_11C;  // 0 loads, 1 stores
    u32 unk_120;  // 0 loads, 1 stores
    u32 unk_124;  // 0 loads, 1 stores
    u8 pad_128[0x44];
    u32 unk_16C;  // 3 loads, 1 stores
    u32 unk_170;  // 4 loads, 2 stores
    u8 pad_174[0x2B0];
    u32 unk_424;  // 0 loads, 1 stores
    u32 unk_428;  // 0 loads, 1 stores
    u32 unk_42C;  // 0 loads, 1 stores
    f32 unk_430;  // 0 loads, 1 stores
    u8 pad_434[0x28C];
    f32 unk_6C0;  // 1 loads, 1 stores
    u8 pad_6C4[0x8];
    u32 unk_6CC;  // 2 loads, 1 stores
    u32 unk_6D0;  // 0 loads, 1 stores
    u32 unk_6D4;  // 5 loads, 2 stores
    u8 pad_6D8[0x418];
    f32 unk_AF0;  // 0 loads, 1 stores
    u8 pad_AF4[0xE0];
    u32 unk_BD4;  // 2 loads, 1 stores
    u32 unk_BD8;  // 0 loads, 1 stores
    u8 pad_BDC[0x528];
    u32 unk_1104;  // 0 loads, 1 stores
    u32 unk_1108;  // 1 loads, 0 stores
    u8 pad_110C[0x4];
    u32 unk_1110;  // 0 loads, 1 stores
    u8 pad_1114[0x470];
    u32 unk_1584;  // 1 loads, 1 stores
    u32 unk_1588;  // 0 loads, 1 stores
    u8 pad_158C[0x320];
    u32 unk_18AC;  // 0 loads, 1 stores
    u8 pad_18B0[0x3A8];
    u32 unk_1C58;  // 7 loads, 2 stores
    u32 unk_1C5C;  // 7 loads, 2 stores
    u8 pad_1C60[0x5FC];
    u32 unk_225C;  // 0 loads, 1 stores
    u32 unk_2260;  // 0 loads, 1 stores
    u8 pad_2264[0x4C0];
    u32 unk_2724;  // 3 loads, 2 stores
} Obj_1_data_2A7E0_At3C;
typedef struct {
    u16 unk_0;  // 10 loads, 0 stores
    u32 unk_2;  // 0 loads, 1 stores
    u8 pad_6[0x16];
    f32 unk_1C;  // 6 loads, 0 stores
    u8 pad_20[0xC];
    u32 unk_2C;  // 0 loads, 3 stores
    u8 pad_30[0x4];
    u32 unk_34;  // 0 loads, 1 stores
    u32 unk_38;  // 1 loads, 0 stores
    Obj_1_data_2A7E0_At3C *unk_3C;  // 75 loads, 0 stores
    u8 pad_40[0x8];
    u32 unk_48;  // 2 loads, 1 stores
    u32 unk_4C;  // 2 loads, 1 stores
    u32 unk_50;  // 3 loads, 1 stores
    u32 unk_54;  // 0 loads, 2 stores
    u32 unk_58;  // 0 loads, 1 stores
    u32 unk_5C;  // 3 loads, 1 stores
    u32 unk_60;  // 5 loads, 1 stores
    u32 unk_64;  // 0 loads, 1 stores
    u32 unk_68;  // 2 loads, 1 stores
    u32 unk_6C;  // 2 loads, 1 stores
    u8 unk_70;  // 3 loads, 2 stores
    u8 pad_71[0x3];
    u32 unk_74;  // 2 loads, 2 stores
    u32 unk_78;  // 3 loads, 0 stores
    u32 unk_7C;  // 5 loads, 1 stores
    u32 unk_80;  // 3 loads, 1 stores
    u8 pad_84[0x4];
    u32 unk_88;  // 3 loads, 0 stores
    u32 unk_8C;  // 1 loads, 0 stores
    u8 pad_90[0xC];
    f32 unk_9C;  // 2 loads, 1 stores
    u16 unk_A0;  // 2 loads, 0 stores
} Obj_1_data_2A7E0;
extern Obj_1_data_2A7E0 lbl_1_data_2A7E0;

// lbl_1_bss_3C30: .bss size 0x14BC, referenced by 95 functions, shape {'object': 332}
typedef struct {
    u32 unk_0;  // 31 loads, 5 stores
    u8 unk_4;  // 3 loads, 0 stores
    u8 unk_5;  // 34 loads, 2 stores
    u8 unk_6;  // 12 loads, 0 stores
    u8 unk_7;  // 1 loads, 0 stores
    u8 unk_8;  // 47 loads, 0 stores
    u8 unk_9;  // 55 loads, 0 stores
    u8 pad_A[0x3];
    u8 unk_D;  // 1 loads, 0 stores
    u8 unk_E;  // 4 loads, 0 stores
    u8 unk_F;  // 1 loads, 0 stores
    u8 pad_10[0x1C];
    u32 unk_2C;  // 1 loads, 0 stores
    u8 pad_30[0x74];
    u16 unk_A4;  // 2 loads, 0 stores
    u8 unk_A6;  // 3 loads, 0 stores
    u8 unk_A7;  // 39 loads, 0 stores
    u8 pad_A8[0x30];
    u16 unk_D8;  // 1 loads, 4 stores
    u16 unk_DA;  // 1 loads, 2 stores
    u8 unk_DC;  // 2 loads, 2 stores
    u8 pad_DD[0x43];
    u16 unk_120;  // 1 loads, 0 stores
    u8 pad_122[0x2A];
    u32 unk_14C;  // 1 loads, 2 stores
    u8 pad_150[0x6];
    u8 unk_156;  // 1 loads, 0 stores
    u8 unk_157;  // 0 loads, 2 stores
    u8 pad_158[0x1A];
    u16 unk_172;  // 0 loads, 1 stores
    u8 pad_174[0x4];
    u16 unk_178;  // 0 loads, 1 stores
    u8 pad_17A[0x2];
    u8 unk_17C;  // 0 loads, 1 stores
    u8 pad_17D[0x7A];
    u8 unk_1F7;  // 0 loads, 1 stores
    u8 pad_1F8[0x20];
    u16 unk_218;  // 0 loads, 1 stores
    u8 pad_21A[0x2];
    u8 unk_21C;  // 0 loads, 1 stores
    u8 pad_21D[0x7A];
    u8 unk_297;  // 0 loads, 1 stores
    u8 pad_298[0x20];
    u16 unk_2B8;  // 0 loads, 1 stores
    u8 pad_2BA[0x2];
    u8 unk_2BC;  // 0 loads, 1 stores
    u8 pad_2BD[0x7A];
    u8 unk_337;  // 0 loads, 1 stores
    u8 pad_338[0x20];
    u16 unk_358;  // 0 loads, 1 stores
    u8 pad_35A[0x2];
    u8 unk_35C;  // 0 loads, 1 stores
    u8 pad_35D[0x7A];
    u8 unk_3D7;  // 0 loads, 1 stores
    u8 pad_3D8[0x20];
    u16 unk_3F8;  // 0 loads, 1 stores
    u8 pad_3FA[0x2];
    u8 unk_3FC;  // 0 loads, 1 stores
    u8 pad_3FD[0x7A];
    u8 unk_477;  // 0 loads, 1 stores
    u8 pad_478[0xF1C];
    u8 unk_1394;  // 1 loads, 0 stores
    u8 pad_1395[0x5F];
    u8 unk_13F4;  // 4 loads, 1 stores
    u8 unk_13F5;  // 3 loads, 1 stores
    u8 unk_13F6;  // 2 loads, 0 stores
    u8 pad_13F7[0x1];
    u16 unk_13F8;  // 0 loads, 1 stores
    u16 unk_13FA;  // 0 loads, 1 stores
    u16 unk_13FC;  // 0 loads, 1 stores
    u16 unk_13FE;  // 0 loads, 1 stores
    u16 unk_1400;  // 0 loads, 1 stores
    u8 unk_1402;  // 0 loads, 1 stores
    u8 pad_1403[0x2];
    u8 unk_1405;  // 2 loads, 0 stores
    u8 pad_1406[0x5E];
    u32 unk_1464;  // 5 loads, 1 stores
    u8 pad_1468[0x4];
    u8 unk_146C;  // 1 loads, 1 stores
    u8 unk_146D;  // 1 loads, 1 stores
    u16 unk_146E;  // 1 loads, 1 stores
    u8 unk_1470;  // 1 loads, 1 stores
    u8 pad_1471[0x3];
    u32 unk_1474;  // 3 loads, 1 stores
    u16 unk_1478;  // 1 loads, 1 stores
    u16 unk_147A;  // 0 loads, 1 stores
    u16 unk_147C;  // 0 loads, 1 stores
    u16 unk_147E;  // 0 loads, 1 stores
    u32 unk_1480;  // 1 loads, 1 stores
    u32 unk_1484;  // 0 loads, 1 stores
    u32 unk_1488;  // 0 loads, 1 stores
    u32 unk_148C;  // 0 loads, 1 stores
    u32 unk_1490;  // 0 loads, 1 stores
    u32 unk_1494;  // 0 loads, 1 stores
    u32 unk_1498;  // 0 loads, 1 stores
    u32 unk_149C;  // 0 loads, 1 stores
    u32 unk_14A0;  // 0 loads, 1 stores
    u32 unk_14A4;  // 0 loads, 1 stores
    u32 unk_14A8;  // 1 loads, 1 stores
} Obj_1_bss_3C30;
extern Obj_1_bss_3C30 lbl_1_bss_3C30;

// lbl_1_bss_8B3A0: .bss size 0x14C, referenced by 87 functions, shape {'object': 204}
typedef struct {
    u32 unk_0;  // 8 loads, 0 stores
    u16 unk_4;  // 13 loads, 0 stores
    /* overlap at 0x5 */
    u8 unk_5;  // 2 loads, 0 stores
    u8 pad_6[0x2];
    u16 unk_8;  // 7 loads, 2 stores
    u8 pad_A[0x4];
    u16 unk_E;  // 15 loads, 0 stores
    u8 pad_10[0x4];
    u8 unk_14;  // 5 loads, 2 stores
    u8 pad_15[0x19];
    u16 unk_2E;  // 1 loads, 0 stores
    u8 pad_30[0x5C];
    u16 unk_8C;  // 2 loads, 0 stores
    u8 pad_8E[0x2];
    u16 unk_90;  // 15 loads, 0 stores
    u16 unk_92;  // 1 loads, 0 stores
    u32 unk_94;  // 60 loads, 3 stores
    u8 pad_98[0x6];
    u8 unk_9E;  // 7 loads, 0 stores
    u8 unk_9F;  // 8 loads, 3 stores
    u8 pad_A0[0x4];
    u32 unk_A4;  // 4 loads, 0 stores
    u8 pad_A8[0x38];
    u32 unk_E0;  // 0 loads, 1 stores
    u32 unk_E4;  // 0 loads, 1 stores
    u32 unk_E8;  // 0 loads, 1 stores
    u32 unk_EC;  // 0 loads, 1 stores
    u32 unk_F0;  // 0 loads, 1 stores
    u32 unk_F4;  // 0 loads, 1 stores
    u32 unk_F8;  // 0 loads, 1 stores
    u32 unk_FC;  // 0 loads, 1 stores
    u32 unk_100;  // 0 loads, 1 stores
    u32 unk_104;  // 0 loads, 1 stores
    u32 unk_108;  // 0 loads, 1 stores
    u32 unk_10C;  // 0 loads, 1 stores
    u32 unk_110;  // 0 loads, 1 stores
    u32 unk_114;  // 0 loads, 1 stores
    u32 unk_118;  // 0 loads, 1 stores
    u32 unk_11C;  // 0 loads, 1 stores
    u32 unk_120;  // 0 loads, 2 stores
    u32 unk_124;  // 1 loads, 2 stores
    u8 unk_128;  // 0 loads, 1 stores
    u8 unk_129;  // 1 loads, 2 stores
    u8 pad_12A[0x2];
    u16 unk_12C;  // 4 loads, 0 stores
    u16 unk_12E;  // 1 loads, 0 stores
    u16 unk_130;  // 1 loads, 0 stores
    u16 unk_132;  // 1 loads, 0 stores
    u16 unk_134;  // 1 loads, 0 stores
    u16 unk_136;  // 1 loads, 0 stores
    u16 unk_138;  // 1 loads, 0 stores
    u16 unk_13A;  // 1 loads, 0 stores
    u16 unk_13C;  // 1 loads, 0 stores
    u8 pad_13E[0x2];
    u32 unk_140;  // 3 loads, 0 stores
    u8 pad_144[0x2];
    u16 unk_146;  // 4 loads, 0 stores
    u16 unk_148;  // 2 loads, 0 stores
} Obj_1_bss_8B3A0;
extern Obj_1_bss_8B3A0 lbl_1_bss_8B3A0;

// lbl_1_bss_3BE0: .bss size 0x4, referenced by 77 functions, shape {'object': 255, 'pointer': 56}
typedef struct {
    u32 unk_0;  // 7 loads, 0 stores
    f32 unk_4;  // 1 loads, 0 stores
    u32 unk_8;  // 14 loads, 0 stores
    u32 unk_C;  // 34 loads, 0 stores
    u8 pad_10[0x4];
    u32 unk_14;  // 2 loads, 1 stores
    u32 unk_18;  // 8 loads, 0 stores
    u32 unk_1C;  // 10 loads, 0 stores
    u8 pad_20[0x4];
    u32 unk_24;  // 2 loads, 1 stores
    u8 pad_28[0x4];
    u32 unk_2C;  // 1 loads, 1 stores
    u8 pad_30[0xC];
    u32 unk_3C;  // 1 loads, 1 stores
    u8 pad_40[0x4];
    u32 unk_44;  // 1 loads, 1 stores
    u32 unk_48;  // 18 loads, 0 stores
    u32 unk_4C;  // 1 loads, 0 stores
    u32 unk_50;  // 1 loads, 0 stores
    u32 unk_54;  // 31 loads, 0 stores
    u8 pad_58[0x4];
    u32 unk_5C;  // 1 loads, 0 stores
    u32 unk_60;  // 1 loads, 1 stores
    u32 unk_64;  // 3 loads, 0 stores
    u32 unk_68;  // 5 loads, 1 stores
    u32 unk_6C;  // 1 loads, 0 stores
    u32 unk_70;  // 2 loads, 1 stores
    u32 unk_74;  // 1 loads, 0 stores
    u32 unk_78;  // 1 loads, 1 stores
    u8 pad_7C[0x1];
    u8 unk_7D;  // 7 loads, 0 stores
    u8 pad_7E[0x2];
    u32 unk_80;  // 4 loads, 1 stores
    u32 unk_84;  // 1 loads, 1 stores
    u32 unk_88;  // 1 loads, 0 stores
    u32 unk_8C;  // 1 loads, 1 stores
    u32 unk_90;  // 6 loads, 1 stores
    u8 pad_94[0x4];
    u32 unk_98;  // 1 loads, 1 stores
    u8 pad_9C[0x4];
    u32 unk_A0;  // 1 loads, 1 stores
    u32 unk_A4;  // 7 loads, 0 stores
    u32 unk_A8;  // 6 loads, 1 stores
    u32 unk_AC;  // 1 loads, 0 stores
    u32 unk_B0;  // 2 loads, 1 stores
    u32 unk_B4;  // 5 loads, 0 stores
    u32 unk_B8;  // 3 loads, 1 stores
    u32 unk_BC;  // 4 loads, 1 stores
    u8 pad_C0[0x10];
    u32 unk_D0;  // 2 loads, 0 stores
    u32 unk_D4;  // 2 loads, 0 stores
} Obj_1_bss_3BE0_Target;
extern Obj_1_bss_3BE0_Target *lbl_1_bss_3BE0;

// lbl_1_bss_9F8: .bss size 0x50, referenced by 67 functions, shape {'object': 279}
typedef struct {
    u16 unk_0;  // 12 loads, 0 stores
    u16 unk_2;  // 14 loads, 0 stores
    u8 pad_4[0x4];
    u16 unk_8;  // 88 loads, 0 stores
    u16 unk_A;  // 20 loads, 0 stores
    u8 pad_C[0x4];
    u16 unk_10;  // 41 loads, 0 stores
    u16 unk_12;  // 41 loads, 0 stores
    u16 unk_14;  // 8 loads, 0 stores
    u16 unk_16;  // 20 loads, 0 stores
    u8 pad_18[0x4];
    u16 unk_1C;  // 9 loads, 0 stores
    u8 pad_1E[0x6];
    u16 unk_24;  // 12 loads, 0 stores
    u16 unk_26;  // 7 loads, 0 stores
    u8 pad_28[0x8];
    u16 unk_30;  // 1 loads, 0 stores
    u8 pad_32[0x12];
    u16 unk_44;  // 1 loads, 0 stores
} Obj_1_bss_9F8;
extern Obj_1_bss_9F8 lbl_1_bss_9F8;

// lbl_1_bss_7F0C0: .bss size 0x5360, referenced by 66 functions, shape {'object': 148}
typedef struct {
    u32 unk_0;  // 4 loads, 1 stores
    u32 unk_4;  // 4 loads, 1 stores
    u32 unk_8;  // 2 loads, 1 stores
    u32 unk_C;  // 2 loads, 1 stores
    u32 unk_10;  // 2 loads, 1 stores
    u32 unk_14;  // 2 loads, 1 stores
    u32 unk_18;  // 3 loads, 1 stores
    u32 unk_1C;  // 3 loads, 1 stores
    u32 unk_20;  // 3 loads, 1 stores
    u32 unk_24;  // 3 loads, 1 stores
    u32 unk_28;  // 3 loads, 1 stores
    u32 unk_2C;  // 3 loads, 1 stores
    u8 pad_30[0x18];
    u32 unk_48;  // 3 loads, 3 stores
    u32 unk_4C;  // 3 loads, 3 stores
    u32 unk_50;  // 3 loads, 3 stores
    u32 unk_54;  // 3 loads, 3 stores
    u32 unk_58;  // 3 loads, 3 stores
    u32 unk_5C;  // 3 loads, 3 stores
    u8 pad_60[0x8];
    u16 unk_68;  // 2 loads, 2 stores
    u16 unk_6A;  // 3 loads, 3 stores
    u8 pad_6C[0x488C];
    u32 unk_48F8;  // 2 loads, 2 stores
    u8 pad_48FC[0x4];
    u32 unk_4900;  // 10 loads, 12 stores
    u32 unk_4904;  // 3 loads, 2 stores
    u8 pad_4908[0x8];
    u32 unk_4910;  // 9 loads, 9 stores
    u32 unk_4914;  // 4 loads, 3 stores
} Obj_1_bss_7F0C0;
extern Obj_1_bss_7F0C0 lbl_1_bss_7F0C0;

// lbl_1_bss_6D838: .bss size 0x4, referenced by 66 functions, shape {'object': 72, 'pointer': 1}
extern u32 lbl_1_bss_6D838;

// lbl_1_bss_3C00: .bss size 0x4, referenced by 58 functions, shape {'object': 1971}
extern u8 lbl_1_bss_3C00;

// lbl_1_bss_38458: .bss size 0x4, referenced by 43 functions, shape {'object': 62, 'pointer': 9}
typedef struct {
    u8 pad_0[0x8];
    u32 unk_8;  // 49 loads, 0 stores
} Obj_1_bss_38458_Target;
extern Obj_1_bss_38458_Target *lbl_1_bss_38458;

// lbl_1_bss_F68: .bss size 0x4, referenced by 42 functions, shape {'object': 140, 'pointer': 6}
typedef struct {
    u32 unk_0;  // 9 loads, 1 stores
    u8 pad_4[0x1E];
    u16 unk_22;  // 3 loads, 3 stores
    u16 unk_24;  // 0 loads, 1 stores
    u8 pad_26[0x1E];
    u16 unk_44;  // 1 loads, 1 stores
    u16 unk_46;  // 0 loads, 1 stores
    u8 unk_48;  // 29 loads, 13 stores
    u8 unk_49;  // 2 loads, 1 stores
    u8 unk_4A;  // 2 loads, 1 stores
    u8 unk_4B;  // 2 loads, 1 stores
    u8 unk_4C;  // 2 loads, 1 stores
    u8 unk_4D;  // 1 loads, 1 stores
    u8 pad_4E[0x2];
    u32 unk_50;  // 5 loads, 1 stores
    u32 unk_54;  // 2 loads, 1 stores
    f32 unk_58;  // 0 loads, 1 stores
    f32 unk_5C;  // 0 loads, 1 stores
} Obj_1_bss_F68_Target;
extern Obj_1_bss_F68_Target *lbl_1_bss_F68;

// lbl_1_data_1D628: .data size 0x4, referenced by 41 functions, shape {'object': 185}
extern u32 lbl_1_data_1D628;

// lbl_1_bss_4B9CC: .bss size 0x5C, referenced by 38 functions, shape {'object': 236}
typedef struct {
    f32 unk_0;  // 2 loads, 9 stores
    f32 unk_4;  // 3 loads, 8 stores
    f32 unk_8;  // 2 loads, 7 stores
    u16 unk_C;  // 9 loads, 7 stores
    u16 unk_E;  // 2 loads, 3 stores
    u32 unk_10;  // 2 loads, 9 stores
    u32 unk_14;  // 0 loads, 6 stores
    f32 unk_18;  // 2 loads, 3 stores
    f32 unk_1C;  // 7 loads, 15 stores
    f32 unk_20;  // 3 loads, 11 stores
    f32 unk_24;  // 0 loads, 3 stores
    f32 unk_28;  // 2 loads, 3 stores
    u32 unk_2C;  // 11 loads, 11 stores
    u16 unk_30;  // 0 loads, 2 stores
    u16 unk_32;  // 0 loads, 3 stores
    u16 unk_34;  // 0 loads, 3 stores
    u8 unk_36;  // 0 loads, 3 stores
    u8 unk_37;  // 0 loads, 4 stores
    f32 unk_38;  // 0 loads, 3 stores
    f32 unk_3C;  // 6 loads, 3 stores
    f32 unk_40;  // 1 loads, 3 stores
    u8 unk_44;  // 3 loads, 3 stores
    u8 unk_45;  // 3 loads, 3 stores
    u8 unk_46;  // 6 loads, 3 stores
    u8 unk_47;  // 3 loads, 3 stores
    u16 unk_48;  // 3 loads, 3 stores
    u16 unk_4A;  // 3 loads, 3 stores
    u16 unk_4C;  // 3 loads, 3 stores
    u16 unk_4E;  // 3 loads, 3 stores
    f32 unk_50;  // 0 loads, 3 stores
    u32 unk_54;  // 2 loads, 3 stores
    u32 unk_58;  // 3 loads, 3 stores
} Obj_1_bss_4B9CC;
extern Obj_1_bss_4B9CC lbl_1_bss_4B9CC;

// lbl_1_bss_6EA98: .bss size 0x4, referenced by 33 functions, shape {'object': 546}
extern u32 lbl_1_bss_6EA98;

// lbl_1_bss_716C0: .bss size 0x8, referenced by 32 functions, shape {'object': 581}
extern u8 lbl_1_bss_716C0;

// lbl_1_data_3FFBC: .data size 0x574, referenced by 31 functions, shape {}
typedef struct {
    u8 unk_0;  // no field accesses recovered
} Obj_1_data_3FFBC;
extern Obj_1_data_3FFBC lbl_1_data_3FFBC;

// lbl_1_bss_7B180: .bss size 0x8, referenced by 29 functions, shape {'object': 857}
typedef struct {
    u32 unk_0;  // 8 loads, 3 stores
    u32 unk_4;  // 2 loads, 2 stores
} Obj_1_bss_7B180;
extern Obj_1_bss_7B180 lbl_1_bss_7B180;

// lbl_1_data_3D544: .data size 0x10, referenced by 26 functions, shape {'object': 8}
typedef struct {
    u32 unk_0;  // 4 loads, 2 stores
    /* overlap at 0x3 */
    u8 unk_3;  // 1 loads, 0 stores
    u8 pad_4[0x4];
    u8 unk_8;  // 1 loads, 0 stores
} Obj_1_data_3D544;
extern Obj_1_data_3D544 lbl_1_data_3D544;

// lbl_1_data_40530: .data size 0x6C, referenced by 26 functions, shape {}
typedef struct {
    u8 unk_0;  // no field accesses recovered
} Obj_1_data_40530;
extern Obj_1_data_40530 lbl_1_data_40530;

// lbl_1_data_35AC8: .data size 0x4, referenced by 25 functions, shape {'object': 12}
extern u32 lbl_1_data_35AC8;

// lbl_1_bss_6C7A4: .bss size 0x28, referenced by 23 functions, shape {'object': 83}
typedef struct {
    u32 unk_0;  // 5 loads, 0 stores
    u32 unk_4;  // 5 loads, 2 stores
    /* overlap at 0x5 */
    u8 unk_5;  // 0 loads, 1 stores
    u8 unk_6;  // 0 loads, 1 stores
    u8 unk_7;  // 0 loads, 1 stores
    f32 unk_8;  // 9 loads, 2 stores
    u32 unk_C;  // 6 loads, 1 stores
    /* overlap at 0xD */
    u8 unk_D;  // 1 loads, 1 stores
    u8 unk_E;  // 1 loads, 1 stores
    u8 unk_F;  // 1 loads, 0 stores
    u32 unk_10;  // 6 loads, 1 stores
    /* overlap at 0x11 */
    u8 unk_11;  // 1 loads, 1 stores
    u8 unk_12;  // 0 loads, 1 stores
    u8 unk_13;  // 0 loads, 1 stores
    u32 unk_14;  // 5 loads, 1 stores
    /* overlap at 0x15 */
    u8 unk_15;  // 0 loads, 1 stores
    u8 unk_16;  // 0 loads, 1 stores
    u8 pad_17[0x1];
    f32 unk_18;  // 5 loads, 1 stores
    f32 unk_1C;  // 5 loads, 1 stores
    u32 unk_20;  // 6 loads, 1 stores
    u32 unk_24;  // 6 loads, 1 stores
} Obj_1_bss_6C7A4;
extern Obj_1_bss_6C7A4 lbl_1_bss_6C7A4;

// lbl_1_bss_6D820: .bss size 0x4, referenced by 23 functions, shape {'object': 280}
extern u8 lbl_1_bss_6D820;

// lbl_1_bss_7EFD8: .bss size 0x44, referenced by 22 functions, shape {'object': 121}
// object reached through lbl_1_bss_7EFD8.unk_40
typedef struct {
    u8 unk_0;  // 1 loads, 0 stores
    u8 pad_1[0x97];
    u32 unk_98;  // 1 loads, 1 stores
    u32 unk_9C;  // 1 loads, 1 stores
    u16 unk_A0;  // 5 loads, 4 stores
    u16 unk_A2;  // 1 loads, 0 stores
} Obj_1_bss_7EFD8_At40;
typedef struct {
    u32 unk_0;  // 11 loads, 8 stores
    u32 unk_4;  // 1 loads, 2 stores
    u32 unk_8;  // 2 loads, 1 stores
    u32 unk_C;  // 3 loads, 1 stores
    u32 unk_10;  // 0 loads, 2 stores
    u32 unk_14;  // 2 loads, 2 stores
    u8 unk_18;  // 1 loads, 1 stores
    u8 unk_19;  // 0 loads, 4 stores
    u8 unk_1A;  // 1 loads, 3 stores
    u8 unk_1B;  // 1 loads, 3 stores
    u8 unk_1C;  // 0 loads, 2 stores
    u8 unk_1D;  // 0 loads, 1 stores
    u8 unk_1E;  // 0 loads, 1 stores
    u8 unk_1F;  // 0 loads, 1 stores
    u8 unk_20;  // 0 loads, 3 stores
    u8 unk_21;  // 0 loads, 2 stores
    u8 unk_22;  // 0 loads, 2 stores
    u8 unk_23;  // 0 loads, 2 stores
    u8 unk_24;  // 1 loads, 1 stores
    u8 unk_25;  // 0 loads, 1 stores
    u8 unk_26;  // 0 loads, 1 stores
    u8 unk_27;  // 0 loads, 1 stores
    u32 unk_28;  // 1 loads, 0 stores
    u8 pad_2C[0xC];
    u8 unk_38;  // 1 loads, 0 stores
    u8 pad_39[0x3];
    u8 unk_3C;  // 1 loads, 0 stores
    u8 pad_3D[0x3];
    Obj_1_bss_7EFD8_At40 *unk_40;  // 50 loads, 0 stores
} Obj_1_bss_7EFD8;
extern Obj_1_bss_7EFD8 lbl_1_bss_7EFD8;

// lbl_1_bss_6EAB4: .bss size 0x12, referenced by 21 functions, shape {'object': 53}
typedef struct {
    u32 unk_0;  // 27 loads, 26 stores
} Obj_1_bss_6EAB4;
extern Obj_1_bss_6EAB4 lbl_1_bss_6EAB4;

// lbl_1_data_5730: .data size 0xC, referenced by 21 functions, shape {'object': 94}
typedef struct {
    u8 unk_0;  // no field accesses recovered
} Obj_1_data_5730;
extern Obj_1_data_5730 lbl_1_data_5730;

// lbl_1_bss_4C688: .bss size 0x2000, referenced by 21 functions, shape {'object': 39}
typedef struct {
    u32 unk_0;  // 3 loads, 3 stores
    u8 pad_4[0x4];
    u32 unk_8;  // 1 loads, 0 stores
    u32 unk_C;  // 1 loads, 0 stores
    u8 pad_10[0x68];
    u32 unk_78;  // 1 loads, 0 stores
    u32 unk_7C;  // 1 loads, 0 stores
    u32 unk_80;  // 8 loads, 3 stores
    u8 pad_84[0x7C];
    u32 unk_100;  // 0 loads, 3 stores
    u8 pad_104[0x7C];
    u32 unk_180;  // 0 loads, 3 stores
    u8 pad_184[0x7C];
    u32 unk_200;  // 0 loads, 3 stores
    u8 pad_204[0x7C];
    u32 unk_280;  // 0 loads, 3 stores
    u8 pad_284[0x7C];
    u32 unk_300;  // 0 loads, 3 stores
    u8 pad_304[0x7C];
    u32 unk_380;  // 0 loads, 3 stores
} Obj_1_bss_4C688;
extern Obj_1_bss_4C688 lbl_1_bss_4C688;

// lbl_1_data_3C7B8: .data size 0xA, referenced by 21 functions, shape {'object': 27}
typedef struct {
    u8 unk_0;  // no field accesses recovered
} Obj_1_data_3C7B8;
extern Obj_1_data_3C7B8 lbl_1_data_3C7B8;

// lbl_1_bss_84420: .bss size 0x8, referenced by 21 functions, shape {'object': 32, 'pointer': 7}
extern u32 lbl_1_bss_84420;

#endif  // REL_MAIN_REL_GLOBALS_H
