#ifndef REL_MAIN_REL_LIGHT_H
#define REL_MAIN_REL_LIGHT_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu light.c`: globals of light.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_data_1EEB0: .data size 0xC, 2 refs from light.c (own data block)
extern u8 lbl_1_data_1EEB0[0xC];

// lbl_1_bss_6D7E8: .bss size 0x8, 2 refs from light.c
extern u32 lbl_1_bss_6D7E8;

// lbl_1_bss_6D7A8: .bss size 0x18, 2 refs from light.c
typedef struct {
    u16 unk_0;  // 1 loads, 1 stores
    u16 unk_2;  // 1 loads, 1 stores
    u16 unk_4;  // 1 loads, 1 stores
    u8 pad_6[0x2];
    u32 unk_8;  // 3 loads, 1 stores
    u32 unk_C;  // 3 loads, 1 stores
    u32 unk_10;  // 2 loads, 1 stores
    u16 unk_14;  // 4 loads, 3 stores
    u16 unk_16;  // 5 loads, 4 stores
} Obj_1_bss_6D7A8;
extern Obj_1_bss_6D7A8 lbl_1_bss_6D7A8;

// lbl_1_data_1EE44: .data size 0x2C, 1 refs from light.c (own data block)
extern u8 lbl_1_data_1EE44[0x2C];

// lbl_1_data_1EE70: .data size 0x40, 1 refs from light.c (own data block)
extern u8 lbl_1_data_1EE70[0x40];

#endif  // REL_MAIN_REL_LIGHT_H
