#ifndef REL_MAIN_REL_LIVE_CAMERA_H
#define REL_MAIN_REL_LIVE_CAMERA_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu live_camera.c`: globals of live_camera.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_data_43B8: .data size 0xC, 11 refs from live_camera.c
extern u8 lbl_1_data_43B8[0xC];

// lbl_1_bss_1148: .bss size 0x14, 9 refs from live_camera.c
typedef struct {
    u8 unk_0;  // 0 loads, 1 stores
    u8 pad_1[0x7];
    f32 unk_8;  // 2 loads, 4 stores
    f32 unk_C;  // 2 loads, 5 stores
    f32 unk_10;  // 3 loads, 2 stores
} Obj_1_bss_1148;
extern Obj_1_bss_1148 lbl_1_bss_1148;

// lbl_1_bss_17C4: .bss size 0xC, 4 refs from live_camera.c
typedef struct {
    u32 unk_0;  // 4 loads, 0 stores
    u8 pad_4[0x8];
} Obj_1_bss_17C4;
extern Obj_1_bss_17C4 lbl_1_bss_17C4;

// lbl_1_data_4484: .data size 0x70, 4 refs from live_camera.c (own data block)
typedef struct {
    s16 unk_0;  // 5 loads, 0 stores
    u8 pad_2[0x6E];
} Obj_1_data_4484;
extern Obj_1_data_4484 lbl_1_data_4484;

// lbl_1_data_44F4: .data size 0x14, 3 refs from live_camera.c (own data block)
typedef struct {
    u32 unk_0;  // 3 loads, 0 stores
    u8 pad_4[0x10];
} Obj_1_data_44F4;
extern Obj_1_data_44F4 lbl_1_data_44F4;

// lbl_1_bss_1800: .bss size 0x10, 2 refs from live_camera.c
extern u8 lbl_1_bss_1800[0x10];

// lbl_1_bss_115C: .bss size 0x1, 2 refs from live_camera.c
extern u8 lbl_1_bss_115C;

// lbl_1_bss_525C: .bss size 0x198, 2 refs from live_camera.c
typedef struct {
    u32 unk_0;  // 1 loads, 0 stores
    u8 pad_4[0x1];
    u8 unk_5;  // 1 loads, 0 stores
    u8 pad_6[0x1];
    u8 unk_7;  // 1 loads, 0 stores
    u8 pad_8[0xF0];
    u8 unk_F8;  // 2 loads, 0 stores
    u8 pad_F9[0x98];
    u8 unk_191;  // 2 loads, 0 stores
    u8 unk_192;  // 2 loads, 0 stores
    u8 pad_193[0x5];
} Obj_1_bss_525C;
extern Obj_1_bss_525C lbl_1_bss_525C;

// lbl_1_bss_17D0: .bss size 0x20, 2 refs from live_camera.c
typedef struct {
    f32 unk_0;  // 1 loads, 1 stores
    u8 pad_4[0x4];
    f32 unk_8;  // 1 loads, 1 stores
    f32 unk_C;  // 1 loads, 0 stores
    f32 unk_10;  // 3 loads, 2 stores
    f32 unk_14;  // 2 loads, 0 stores
    u8 pad_18[0x8];
} Obj_1_bss_17D0;
extern Obj_1_bss_17D0 lbl_1_bss_17D0;

// lbl_1_bss_6F243: .bss size 0x1, 2 refs from live_camera.c
extern u8 lbl_1_bss_6F243;

// lbl_1_bss_6EAD0: .bss size 0x708, 2 refs from live_camera.c
typedef struct {
    u32 unk_0;  // 23 loads, 0 stores
    u32 unk_4;  // 9 loads, 0 stores
} Obj_1_bss_6EAD0_At0;
typedef struct {
    Obj_1_bss_6EAD0_At0 *unk_0;  // 34 loads, 0 stores
    u8 pad_4[0x704];
} Obj_1_bss_6EAD0;
extern Obj_1_bss_6EAD0 lbl_1_bss_6EAD0;

// lbl_1_bss_3B28: .bss size 0x4, 2 refs from live_camera.c
extern u32 lbl_1_bss_3B28;

// lbl_1_bss_3B2C: .bss size 0x4, 2 refs from live_camera.c
extern u32 lbl_1_bss_3B2C;

// lbl_1_data_47B4: .data size 0x2EC, 2 refs from live_camera.c (own data block)
typedef struct {
    u8 pad_0[0x18];
    s16 unk_18;  // 1 loads, 0 stores
    u8 pad_1A[0x2];
    u32 unk_1C;  // 2 loads, 0 stores
    u8 pad_20[0x2CC];
} Obj_1_data_47B4;
extern Obj_1_data_47B4 lbl_1_data_47B4;

// lbl_1_data_4AA0: .data size 0x6E0, 2 refs from live_camera.c (own data block)
typedef struct {
    u32 unk_0;  // 1 loads, 0 stores
    u32 unk_4;  // 1 loads, 0 stores
    u32 unk_8;  // 1 loads, 0 stores
    f32 unk_C;  // 1 loads, 0 stores
    f32 unk_10;  // 1 loads, 0 stores
    f32 unk_14;  // 1 loads, 0 stores
    f32 unk_18;  // 1 loads, 0 stores
    u8 pad_1C[0x6C4];
} Obj_1_data_4AA0;
extern Obj_1_data_4AA0 lbl_1_data_4AA0;

// lbl_1_bss_17F8: .bss size 0x8, 2 refs from live_camera.c
extern u32 lbl_1_bss_17F8;

// lbl_1_bss_17B0: .bss size 0x4, 2 refs from live_camera.c
extern u32 lbl_1_bss_17B0;

// lbl_1_data_4754: .data size 0x60, 2 refs from live_camera.c (own data block)
typedef struct {
    u8 pad_0[0xC];
    s16 unk_C;  // 1 loads, 0 stores
    u8 pad_E[0x52];
} Obj_1_data_4754;
extern Obj_1_data_4754 lbl_1_data_4754;

// lbl_1_bss_3B30: .bss size 0x8C, 2 refs from live_camera.c
typedef struct {
    u32 unk_0;  // 1 loads, 0 stores
    u8 pad_4[0x7C];
    u32 unk_80;  // 0 loads, 1 stores
    u32 unk_84;  // 0 loads, 1 stores
    u8 pad_88[0x4];
} Obj_1_bss_3B30;
extern Obj_1_bss_3B30 lbl_1_bss_3B30;

// lbl_1_data_4440: .data size 0x44, 2 refs from live_camera.c (own data block)
extern u8 lbl_1_data_4440[0x44];

// lbl_1_data_5184: .data size 0x4, 1 refs from live_camera.c (own data block)
extern u32 lbl_1_data_5184;

// lbl_1_data_5180: .data size 0x4, 1 refs from live_camera.c (own data block)
extern u32 lbl_1_data_5180;

// lbl_1_data_4420: .data size 0xE, 1 refs from live_camera.c (own data block)
extern u8 lbl_1_data_4420[0xE];

// lbl_1_data_4430: .data size 0xF, 1 refs from live_camera.c (own data block)
extern u8 lbl_1_data_4430[0xF];

#endif  // REL_MAIN_REL_LIVE_CAMERA_H
