#ifndef REL_MAIN_REL_LOAD_H
#define REL_MAIN_REL_LOAD_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu load.c`: globals of load.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_bss_384C0: .bss size 0x4, 17 refs from load.c
extern u32 lbl_1_bss_384C0;

// lbl_1_bss_384D8: .bss size 0x5800, 8 refs from load.c
typedef struct {
    u32 unk_0;  // 6 loads, 8 stores
    u32 unk_4;  // 12 loads, 0 stores
    u32 unk_8;  // 12 loads, 0 stores
    u32 unk_C;  // 24 loads, 0 stores
    u32 unk_10;  // 26 loads, 0 stores
    u8 pad_14[0x57EC];
} Obj_1_bss_384D8;
extern Obj_1_bss_384D8 lbl_1_bss_384D8;

// lbl_1_bss_3DCDC: .bss size 0x8, 4 refs from load.c
extern u32 lbl_1_bss_3DCDC;

// lbl_1_bss_3DFF4: .bss size 0xC, 3 refs from load.c
typedef struct {
    u32 unk_0;  // 2 loads, 1 stores
    u8 pad_4[0x8];
} Obj_1_bss_3DFF4;
extern Obj_1_bss_3DFF4 lbl_1_bss_3DFF4;

// lbl_1_bss_384D0: .bss size 0x8, 3 refs from load.c
extern u32 lbl_1_bss_384D0;

// lbl_1_data_6730: .data size 0x4C, 3 refs from load.c (own data block)
extern u8 lbl_1_data_6730[0x4C];

// lbl_1_data_67F0: .data size 0x4B0, 2 refs from load.c (own data block)
typedef struct {
    u32 unk_0;  // 2 loads, 0 stores
    u32 unk_4;  // 1 loads, 0 stores
    u8 pad_8[0x4A8];
} Obj_1_data_67F0;
extern Obj_1_data_67F0 lbl_1_data_67F0;

// lbl_1_data_6CA0: .data size 0x24, 2 refs from load.c (own data block)
typedef struct {
    u32 unk_0;  // 3 loads, 2 stores
    u32 unk_4;  // 2 loads, 1 stores
    u32 unk_8;  // 2 loads, 0 stores
    u8 pad_C[0x18];
} Obj_1_data_6CA0;
extern Obj_1_data_6CA0 lbl_1_data_6CA0;

// lbl_1_bss_384C8: .bss size 0x4, 2 refs from load.c
extern u32 lbl_1_bss_384C8;

// jumptable_1_data_677C: .data size 0x3C, 1 refs from load.c (own data block)
extern u8 jumptable_1_data_677C[0x3C];

// lbl_1_data_67CC: .data size 0x2, 1 refs from load.c (own data block)
extern u16 lbl_1_data_67CC;

// lbl_1_data_67D0: .data size 0x19, 1 refs from load.c (own data block)
extern u8 lbl_1_data_67D0[0x19];

// lbl_1_data_1A364: .data size 0x4, 1 refs from load.c (own data block)
extern u32 lbl_1_data_1A364;

// lbl_1_data_19FC4: .data size 0x2F0, 1 refs from load.c (own data block)
extern u8 lbl_1_data_19FC4[0x2F0];

// lbl_1_data_19098: .data size 0x2F0, 1 refs from load.c (own data block)
extern u8 lbl_1_data_19098[0x2F0];

#endif  // REL_MAIN_REL_LOAD_H
