#ifndef REL_MAIN_REL_MDLLOAD_H
#define REL_MAIN_REL_MDLLOAD_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu mdlload.c`: globals of mdlload.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_bss_3BC0: .bss size 0x20, 4 refs from mdlload.c
extern u8 lbl_1_bss_3BC0[0x20];

// lbl_1_data_3DBD8: .data size 0xA, 4 refs from mdlload.c (own data block)
extern u8 lbl_1_data_3DBD8[0xA];

#endif  // REL_MAIN_REL_MDLLOAD_H
