#ifndef REL_MAIN_REL_MEMCARD_H
#define REL_MAIN_REL_MEMCARD_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu memcard.c`: globals of memcard.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_bss_716C0: .bss size 0x8, 28 refs from memcard.c
extern u8 lbl_1_bss_716C0[8];

// lbl_1_bss_716C8: .bss size 0x140, 16 refs from memcard.c
typedef struct {
    u8 unk_0;  // 1 loads, 0 stores
    u8 unk_1;  // 4 loads, 0 stores
    u8 pad_2[0x6];
    u32 unk_8;  // 1 loads, 0 stores
    u8 pad_C[0x80];
    u32 unk_8C;  // 1 loads, 0 stores
} Obj_1_bss_716C8_At24;
typedef struct {
    u8 unk_0;  // 6 loads, 0 stores
    u8 unk_1;  // 5 loads, 0 stores
    u8 unk_2;  // 2 loads, 0 stores
    u8 pad_3[0x1];
    u8 unk_4;  // 2 loads, 0 stores
    u8 pad_5[0x2];
    u8 unk_7;  // 0 loads, 1 stores
    u8 pad_8[0x4];
    u32 unk_C;  // 9 loads, 9 stores
    u8 pad_10[0x14];
    Obj_1_bss_716C8_At24 *unk_24;  // 8 loads, 0 stores
    u8 pad_28[0x2];
    u8 unk_2A;  // 2 loads, 0 stores
    u8 pad_2B[0x1D];
    u32 unk_48;  // 1 loads, 2 stores
    u32 unk_4C;  // 1 loads, 2 stores
    u32 unk_50;  // 1 loads, 2 stores
    u8 pad_54[0x44];
    u32 unk_98;  // 2 loads, 2 stores
    u32 unk_9C;  // 2 loads, 2 stores
    u8 pad_A0[0xA0];
} Obj_1_bss_716C8;
extern Obj_1_bss_716C8 lbl_1_bss_716C8;

// lbl_1_bss_77380: .bss size 0x3000, 6 refs from memcard.c
typedef struct {
    u32 unk_0;  // 10 loads, 11 stores
    u32 unk_4;  // 10 loads, 11 stores
    u32 unk_8;  // 10 loads, 11 stores
    u32 unk_C;  // 10 loads, 11 stores
    u32 unk_10;  // 10 loads, 11 stores
    u32 unk_14;  // 10 loads, 11 stores
    u32 unk_18;  // 10 loads, 11 stores
    u32 unk_1C;  // 10 loads, 11 stores
    u32 unk_20;  // 10 loads, 11 stores
    u32 unk_24;  // 12 loads, 12 stores
    u32 unk_28;  // 16 loads, 12 stores
    u32 unk_2C;  // 15 loads, 13 stores
    u32 unk_30;  // 1 loads, 1 stores
    u32 unk_34;  // 1 loads, 1 stores
    u32 unk_38;  // 1 loads, 1 stores
    u32 unk_3C;  // 1 loads, 1 stores
    u32 unk_40;  // 1 loads, 1 stores
    u32 unk_44;  // 1 loads, 1 stores
    u32 unk_48;  // 1 loads, 1 stores
    u32 unk_4C;  // 1 loads, 1 stores
    u32 unk_50;  // 1 loads, 1 stores
    u32 unk_54;  // 1 loads, 1 stores
    u32 unk_58;  // 1 loads, 1 stores
    u32 unk_5C;  // 1 loads, 1 stores
    u32 unk_60;  // 1 loads, 1 stores
    u32 unk_64;  // 1 loads, 1 stores
    u32 unk_68;  // 1 loads, 1 stores
    u32 unk_6C;  // 1 loads, 1 stores
    u32 unk_70;  // 1 loads, 1 stores
    u32 unk_74;  // 1 loads, 1 stores
    u32 unk_78;  // 1 loads, 1 stores
    u32 unk_7C;  // 1 loads, 1 stores
    u32 unk_80;  // 1 loads, 1 stores
    u32 unk_84;  // 1 loads, 1 stores
    u32 unk_88;  // 1 loads, 1 stores
    u32 unk_8C;  // 1 loads, 1 stores
    u32 unk_90;  // 1 loads, 0 stores
    u32 unk_94;  // 1 loads, 0 stores
    u32 unk_98;  // 1 loads, 0 stores
    u32 unk_9C;  // 1 loads, 0 stores
    u32 unk_A0;  // 1 loads, 0 stores
    u32 unk_A4;  // 1 loads, 0 stores
    u32 unk_A8;  // 1 loads, 0 stores
    u32 unk_AC;  // 1 loads, 0 stores
    u32 unk_B0;  // 1 loads, 0 stores
    u32 unk_B4;  // 1 loads, 0 stores
    u32 unk_B8;  // 1 loads, 0 stores
    u32 unk_BC;  // 1 loads, 0 stores
    u8 pad_C0[0x2F40];
} Obj_1_bss_77380;
extern Obj_1_bss_77380 lbl_1_bss_77380;

// lbl_1_data_3C7C4: .data size 0xD8, 5 refs from memcard.c (own data block)
extern u8 lbl_1_data_3C7C4[0xD8];

// lbl_1_bss_718C0: .bss size 0x20, 4 refs from memcard.c
typedef struct {
    u32 unk_0;  // 1 loads, 0 stores
    u8 unk_4;  // 0 loads, 1 stores
    u8 unk_5;  // 0 loads, 1 stores
    u8 unk_6;  // 0 loads, 1 stores
    u8 unk_7;  // 0 loads, 1 stores
    u8 pad_8[0x8];
    u16 unk_10;  // 0 loads, 1 stores
    u8 pad_12[0x4];
    u8 unk_16;  // 0 loads, 1 stores
    u8 pad_17[0x19];
    u16 unk_30;  // 0 loads, 1 stores
    u8 pad_32[0x4];
    u8 unk_36;  // 0 loads, 1 stores
    u8 pad_37[0x19];
    u16 unk_50;  // 0 loads, 1 stores
    u8 pad_52[0x4];
    u8 unk_56;  // 0 loads, 1 stores
    u8 pad_57[0x19];
    u16 unk_70;  // 0 loads, 1 stores
    u8 pad_72[0x4];
    u8 unk_76;  // 0 loads, 1 stores
} Obj_1_bss_718C0_At0;
typedef struct {
    Obj_1_bss_718C0_At0 *unk_0;  // 8 loads, 1 stores
    u8 pad_4[0x1C];
} Obj_1_bss_718C0;
extern Obj_1_bss_718C0 lbl_1_bss_718C0;

// lbl_1_data_3C89C: .data size 0x44, 4 refs from memcard.c (own data block)
extern u8 lbl_1_data_3C89C[0x44];

// lbl_1_bss_962: .bss size 0x2, 4 refs from memcard.c
extern s16 lbl_1_bss_962;

// lbl_1_bss_7AC48: .bss size 0x8, 3 refs from memcard.c
typedef struct {
    u32 unk_0;  // 2 loads, 0 stores
    u8 pad_4[0xC];
    u32 unk_10;  // 4 loads, 4 stores
} Obj_1_bss_7AC48_At0;
typedef struct {
    Obj_1_bss_7AC48_At0 *unk_0;  // 9 loads, 2 stores
    u16 unk_4;  // 4 loads, 1 stores
    u8 pad_6[0x2];
} Obj_1_bss_7AC48;
extern Obj_1_bss_7AC48 lbl_1_bss_7AC48;

// lbl_1_bss_7730A: .bss size 0x1, 3 refs from memcard.c
extern u8 lbl_1_bss_7730A;

// lbl_1_data_3D230: .data size 0x4, 3 refs from memcard.c (own data block)
extern u32 lbl_1_data_3D230;

// lbl_1_data_3D138: .data size 0xC, 2 refs from memcard.c (own data block)
extern u8 lbl_1_data_3D138[0xC];

// lbl_1_bss_718E0: .bss size 0x59E8, 2 refs from memcard.c
typedef struct {
    u16 unk_0;  // 0 loads, 1 stores
    u8 unk_2;  // 2 loads, 1 stores
    u8 unk_3;  // 1 loads, 1 stores
    u8 pad_4[0x2];
    u16 unk_6;  // 0 loads, 1 stores
    u8 pad_8[0x198];
    u16 unk_1A0;  // 0 loads, 1 stores
    u8 pad_1A2[0x537E];
    u16 unk_5520;  // 0 loads, 1 stores
    u8 pad_5522[0x1];
    u8 unk_5523;  // 1 loads, 0 stores
    u8 pad_5524[0x4C4];
} Obj_1_bss_718E0;
extern Obj_1_bss_718E0 lbl_1_bss_718E0;

// lbl_1_data_2AC0: .data size 0x80, 2 refs from memcard.c
extern u8 lbl_1_data_2AC0[0x80];

// lbl_1_data_2B40: .data size 0x10, 2 refs from memcard.c
extern u8 lbl_1_data_2B40[0x10];

// lbl_1_data_2B50: .data size 0x8, 2 refs from memcard.c
extern u32 lbl_1_data_2B50[2];

// lbl_1_data_2B58: .data size 0x8, 2 refs from memcard.c
extern u32 lbl_1_data_2B58[2];

// lbl_1_bss_AA0: .bss size 0x150, 2 refs from memcard.c
extern u8 lbl_1_bss_AA0[0x150];

// lbl_1_data_2B60: .data size 0x4, 2 refs from memcard.c
extern u32 lbl_1_data_2B60;

// lbl_1_data_3D124: .data size 0x13, 2 refs from memcard.c (own data block)
extern u8 lbl_1_data_3D124[0x13];

// lbl_1_bss_718B4: .bss size 0x4, 2 refs from memcard.c
extern u32 lbl_1_bss_718B4;

// lbl_1_bss_7A380: .bss size 0x8, 2 refs from memcard.c
extern u32 lbl_1_bss_7A380[2];

// lbl_1_bss_71808: .bss size 0x4, 2 refs from memcard.c
extern u32 lbl_1_bss_71808;

// lbl_1_data_2BD54: .data size 0xA68, 2 refs from memcard.c
extern u8 lbl_1_data_2BD54[0xA68];

// lbl_1_bss_718B1: .bss size 0x1, 2 refs from memcard.c
extern u8 lbl_1_bss_718B1;

// jumptable_1_data_3CAB4: .data size 0x9C, 1 refs from memcard.c (own data block)
extern u8 jumptable_1_data_3CAB4[0x9C];

// jumptable_1_data_3CB68: .data size 0x9C, 1 refs from memcard.c (own data block)
extern u8 jumptable_1_data_3CB68[0x9C];

// jumptable_1_data_3CD44: .data size 0x9C, 1 refs from memcard.c (own data block)
extern u8 jumptable_1_data_3CD44[0x9C];

// jumptable_1_data_3CC0C: .data size 0x9C, 1 refs from memcard.c (own data block)
extern u8 jumptable_1_data_3CC0C[0x9C];

// lbl_1_data_3D11C: .data size 0x8, 1 refs from memcard.c (own data block)
typedef struct {
    s16 unk_0;  // 1 loads, 0 stores
    s16 unk_2;  // 1 loads, 0 stores
    s16 unk_4;  // 1 loads, 0 stores
    s16 unk_6;  // 1 loads, 0 stores
} Obj_1_data_3D11C;
extern Obj_1_data_3D11C lbl_1_data_3D11C;

// jumptable_1_data_3CA18: .data size 0x9C, 1 refs from memcard.c (own data block)
extern u8 jumptable_1_data_3CA18[0x9C];

// jumptable_1_data_3C980: .data size 0x98, 1 refs from memcard.c (own data block)
extern u8 jumptable_1_data_3C980[0x98];

// jumptable_1_data_3CEF4: .data size 0x24, 1 refs from memcard.c (own data block)
extern u8 jumptable_1_data_3CEF4[0x24];

// lbl_1_data_3D108: .data size 0x11, 1 refs from memcard.c (own data block)
extern u8 lbl_1_data_3D108[0x11];

// lbl_1_data_3CF40: .data size 0xF, 1 refs from memcard.c (own data block)
extern u8 lbl_1_data_3CF40[0xF];

// jumptable_1_data_3C8E0: .data size 0xA0, 1 refs from memcard.c (own data block)
extern u8 jumptable_1_data_3C8E0[0xA0];

// jumptable_1_data_3CCA8: .data size 0x9C, 1 refs from memcard.c (own data block)
extern u8 jumptable_1_data_3CCA8[0x9C];

#endif  // REL_MAIN_REL_MEMCARD_H
