#ifndef REL_MAIN_REL_MOTASGLIST_H
#define REL_MAIN_REL_MOTASGLIST_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu motasglist.c`: globals of motasglist.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_data_6720: .data size 0xD, 2 refs from motasglist.c (own data block)
extern u8 lbl_1_data_6720[0xD];

#endif  // REL_MAIN_REL_MOTASGLIST_H
