#ifndef REL_MAIN_REL_OBJPUT_H
#define REL_MAIN_REL_OBJPUT_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu objput.c`: globals of objput.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_data_1C650: .data size 0x9, 2 refs from objput.c (own data block)
extern u8 lbl_1_data_1C650[0x9];

#endif  // REL_MAIN_REL_OBJPUT_H
