#ifndef REL_MAIN_REL_PHYS_H
#define REL_MAIN_REL_PHYS_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu phys.c`: globals of phys.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_bss_7AE88: .bss size 0x30, 11 refs from phys.c
typedef struct {
    u8 pad_0[0x554];
    f32 unk_554;  // 1 loads, 0 stores
    u8 pad_558[0x24];
    f32 unk_57C;  // 1 loads, 0 stores
    u8 pad_580[0x6C];
    f32 unk_5EC;  // 1 loads, 0 stores
    u8 pad_5F0[0x14EC];
    f32 unk_1ADC;  // 1 loads, 0 stores
    u8 pad_1AE0[0x24];
    f32 unk_1B04;  // 1 loads, 0 stores
    u8 pad_1B08[0x6C];
    f32 unk_1B74;  // 1 loads, 0 stores
    u8 pad_1B78[0xAFC];
    f32 unk_2674;  // 1 loads, 0 stores
    u8 pad_2678[0x24];
    f32 unk_269C;  // 1 loads, 0 stores
    u8 pad_26A0[0x6C];
    f32 unk_270C;  // 1 loads, 0 stores
    u8 pad_2710[0x508C];
    f32 unk_779C;  // 2 loads, 0 stores
    u8 pad_77A0[0x24];
    f32 unk_77C4;  // 2 loads, 0 stores
    u8 pad_77C8[0x6C];
    f32 unk_7834;  // 2 loads, 0 stores
} Obj_1_bss_7AE88_At10;
typedef struct {
    u32 unk_0;  // 13 loads, 3 stores
    s16 unk_4;  // 12 loads, 3 stores
    u8 pad_6[0x2];
    u32 unk_8;  // 12 loads, 3 stores
    s16 unk_C;  // 11 loads, 5 stores
    u8 pad_E[0x2];
    Obj_1_bss_7AE88_At10 *unk_10;  // 20 loads, 3 stores
    s16 unk_14;  // 11 loads, 5 stores
    u8 pad_16[0x2];
    u32 unk_18;  // 12 loads, 3 stores
    s16 unk_1C;  // 11 loads, 3 stores
    u8 pad_1E[0x2];
    u32 unk_20;  // 12 loads, 3 stores
    s16 unk_24;  // 11 loads, 4 stores
    u8 pad_26[0x2];
    u32 unk_28;  // 12 loads, 3 stores
    s16 unk_2C;  // 12 loads, 5 stores
    u8 pad_2E[0x2];
} Obj_1_bss_7AE88;
extern Obj_1_bss_7AE88 lbl_1_bss_7AE88;

// lbl_1_bss_7B188: .bss size 0x8, 6 refs from phys.c
extern u32 lbl_1_bss_7B188;

// lbl_1_data_3E52C: .data size 0x4, 5 refs from phys.c (own data block)
extern u32 lbl_1_data_3E52C;

// lbl_1_data_3E358: .data size 0xC, 5 refs from phys.c (own data block)
extern u8 lbl_1_data_3E358[0xC];

// lbl_1_bss_7AEB8: .bss size 0x294, 4 refs from phys.c
typedef struct {
    u32 unk_0;  // 2 loads, 0 stores
    u8 pad_4[0x1E0];
    s16 unk_1E4;  // 1 loads, 0 stores
    u8 pad_1E6[0x6];
    f32 unk_1EC;  // 1 loads, 0 stores
    f32 unk_1F0;  // 1 loads, 0 stores
    f32 unk_1F4;  // 1 loads, 0 stores
    f32 unk_1F8;  // 1 loads, 0 stores
    f32 unk_1FC;  // 1 loads, 0 stores
    f32 unk_200;  // 1 loads, 0 stores
    f32 unk_204;  // 1 loads, 0 stores
    f32 unk_208;  // 1 loads, 0 stores
    f32 unk_20C;  // 1 loads, 0 stores
    u8 pad_210[0x30];
    u16 unk_240;  // 2 loads, 0 stores
    u16 unk_242;  // 2 loads, 0 stores
    u32 unk_244;  // 1 loads, 0 stores
    u8 pad_248[0xC];
    f32 unk_254;  // 1 loads, 2 stores
    f32 unk_258;  // 0 loads, 2 stores
    f32 unk_25C;  // 0 loads, 1 stores
    f32 unk_260;  // 0 loads, 1 stores
    u8 pad_264[0xC];
    u32 unk_270;  // 1 loads, 0 stores
    u8 pad_274[0x20];
} Obj_1_bss_7AEB8;
extern Obj_1_bss_7AEB8 lbl_1_bss_7AEB8;

// lbl_1_data_3DC98: .data size 0x6, 4 refs from phys.c
extern u32 lbl_1_data_3DC98;

// lbl_1_data_3E184: .data size 0xC, 3 refs from phys.c (own data block)
typedef struct {
    u8 pad_0[0x8];
    f32 unk_8;  // 1 loads, 0 stores
} Obj_1_data_3E184;
extern Obj_1_data_3E184 lbl_1_data_3E184;

// lbl_1_data_3DDB4: .data size 0x88, 3 refs from phys.c (own data block)
extern u8 lbl_1_data_3DDB4[0x88];

// lbl_1_bss_7C85C: .bss size 0x71, 2 refs from phys.c
typedef struct {
    u32 unk_0;  // 2 loads, 2 stores
    u8 pad_4[0x6D];
} Obj_1_bss_7C85C;
extern Obj_1_bss_7C85C lbl_1_bss_7C85C;

// lbl_1_data_3E538: .data size 0x4, 2 refs from phys.c (own data block)
extern u32 lbl_1_data_3E538;

// lbl_1_data_3E5B4: .data size 0x78, 2 refs from phys.c (own data block)
extern u8 lbl_1_data_3E5B4[0x78];

// lbl_1_data_3E150: .data size 0x4, 1 refs from phys.c (own data block)
extern u32 lbl_1_data_3E150;

// lbl_1_data_3DE3C: .data size 0x4, 1 refs from phys.c (own data block)
extern u32 lbl_1_data_3DE3C;

// lbl_1_data_3E530: .data size 0x8, 1 refs from phys.c (own data block)
extern u32 lbl_1_data_3E530;

// lbl_1_data_3E434: .data size 0x44, 1 refs from phys.c (own data block)
extern u8 lbl_1_data_3E434[0x44];

// lbl_1_data_3E154: .data size 0xC, 1 refs from phys.c (own data block)
extern u8 lbl_1_data_3E154[0xC];

// lbl_1_data_3E160: .data size 0x24, 1 refs from phys.c (own data block)
extern u8 lbl_1_data_3E160[0x24];

// lbl_1_data_3E53C: .data size 0x78, 1 refs from phys.c (own data block)
extern u8 lbl_1_data_3E53C[0x78];

// lbl_1_data_3E190: .data size 0x7, 1 refs from phys.c (own data block)
extern u32 lbl_1_data_3E190;

// lbl_1_data_3DE40: .data size 0x128, 1 refs from phys.c (own data block)
extern u8 lbl_1_data_3DE40[0x128];

#endif  // REL_MAIN_REL_PHYS_H
