#ifndef REL_MAIN_REL_PTCLPUT_H
#define REL_MAIN_REL_PTCLPUT_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu ptclput.c`: globals of ptclput.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_bss_6EA88: .bss size 0x8, 4 refs from ptclput.c
typedef struct {
    u32 unk_0;  // 3 loads, 1 stores
    u32 unk_4;  // 3 loads, 1 stores
} Obj_1_bss_6EA88;
extern Obj_1_bss_6EA88 lbl_1_bss_6EA88;

// lbl_1_data_2CD20: .data size 0xA, 2 refs from ptclput.c (own data block)
extern u8 lbl_1_data_2CD20[0xA];

// lbl_1_bss_6EA96: .bss size 0x2, 2 refs from ptclput.c
extern u16 lbl_1_bss_6EA96;

// lbl_1_data_33F0C: .data size 0x10, 1 refs from ptclput.c (own data block)
typedef struct {
    u32 unk_0;  // 2 loads, 0 stores
    u32 unk_4;  // 1 loads, 0 stores
    u32 unk_8;  // 1 loads, 0 stores
    u32 unk_C;  // 2 loads, 0 stores
} Obj_1_data_33F0C;
extern Obj_1_data_33F0C lbl_1_data_33F0C;

#endif  // REL_MAIN_REL_PTCLPUT_H
