#ifndef REL_MAIN_REL_RANKING_H
#define REL_MAIN_REL_RANKING_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu ranking.c`: globals of ranking.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_bss_8F878: .bss size 0x58, 8 refs from ranking.c
typedef struct {
    u8 unk_0;  // 1 loads, 0 stores
    u8 pad_1[0xF];
    u32 unk_10;  // 3 loads, 1 stores
    u32 unk_14;  // 3 loads, 1 stores
    u8 unk_18;  // 0 loads, 1 stores
    u8 unk_19;  // 0 loads, 1 stores
    u8 unk_1A;  // 0 loads, 1 stores
    u8 unk_1B;  // 0 loads, 1 stores
    u8 unk_1C;  // 0 loads, 1 stores
    u8 unk_1D;  // 0 loads, 1 stores
    u8 unk_1E;  // 0 loads, 1 stores
    u8 unk_1F;  // 0 loads, 1 stores
    u8 unk_20;  // 0 loads, 1 stores
    u8 unk_21;  // 0 loads, 1 stores
    u8 unk_22;  // 0 loads, 1 stores
    u8 unk_23;  // 0 loads, 1 stores
    u8 unk_24;  // 0 loads, 1 stores
    u8 unk_25;  // 0 loads, 1 stores
    u8 unk_26;  // 0 loads, 1 stores
    u8 unk_27;  // 0 loads, 1 stores
    u8 unk_28;  // 0 loads, 1 stores
    u8 unk_29;  // 0 loads, 1 stores
    u8 unk_2A;  // 0 loads, 1 stores
    u8 unk_2B;  // 0 loads, 1 stores
    u8 unk_2C;  // 0 loads, 1 stores
    u8 unk_2D;  // 0 loads, 1 stores
    u8 unk_2E;  // 0 loads, 1 stores
    u8 unk_2F;  // 0 loads, 1 stores
    u8 unk_30;  // 0 loads, 1 stores
    u8 pad_31[0x3];
    u32 unk_34;  // 3 loads, 1 stores
    u8 unk_38;  // 1 loads, 1 stores
    u8 unk_39;  // 2 loads, 1 stores
    u8 unk_3A;  // 2 loads, 2 stores
    u8 unk_3B;  // 2 loads, 2 stores
    u8 unk_3C;  // 2 loads, 2 stores
    u8 unk_3D;  // 3 loads, 1 stores
    u8 unk_3E;  // 3 loads, 1 stores
    u8 unk_3F;  // 0 loads, 3 stores
    u8 unk_40;  // 0 loads, 3 stores
    u8 unk_41;  // 0 loads, 3 stores
    u8 unk_42;  // 0 loads, 3 stores
    u8 unk_43;  // 0 loads, 3 stores
    u8 unk_44;  // 0 loads, 3 stores
    u8 unk_45;  // 0 loads, 3 stores
    u8 unk_46;  // 0 loads, 3 stores
    u8 unk_47;  // 0 loads, 3 stores
    u8 unk_48;  // 0 loads, 3 stores
    u8 unk_49;  // 0 loads, 3 stores
    u8 unk_4A;  // 0 loads, 3 stores
    u8 unk_4B;  // 0 loads, 3 stores
    u8 unk_4C;  // 0 loads, 3 stores
    u8 unk_4D;  // 0 loads, 2 stores
    u8 unk_4E;  // 0 loads, 1 stores
    u8 unk_4F;  // 0 loads, 1 stores
    u8 unk_50;  // 0 loads, 1 stores
    u8 unk_51;  // 0 loads, 1 stores
    u8 pad_52[0x6];
} Obj_1_bss_8F878;
extern Obj_1_bss_8F878 lbl_1_bss_8F878;

// lbl_1_bss_8F428: .bss size 0x140, 7 refs from ranking.c
typedef struct {
    u32 unk_0;  // 0 loads, 2 stores
    u32 unk_4;  // 3 loads, 4 stores
    u32 unk_8;  // 0 loads, 3 stores
    u32 unk_C;  // 0 loads, 3 stores
    u32 unk_10;  // 0 loads, 3 stores
    u32 unk_14;  // 0 loads, 3 stores
    u32 unk_18;  // 0 loads, 3 stores
    u32 unk_1C;  // 0 loads, 3 stores
    u32 unk_20;  // 0 loads, 3 stores
    u32 unk_24;  // 0 loads, 3 stores
    u32 unk_28;  // 0 loads, 3 stores
    u32 unk_2C;  // 0 loads, 3 stores
    u8 unk_30;  // 0 loads, 2 stores
    u8 pad_31[0x3];
    f32 unk_34;  // 1 loads, 3 stores
    u8 pad_38[0x14];
    u8 unk_4C;  // 1 loads, 0 stores
    u8 pad_4D[0xF3];
} Obj_1_bss_8F428;
extern Obj_1_bss_8F428 lbl_1_bss_8F428;

// lbl_1_bss_8F568: .bss size 0x10, 5 refs from ranking.c
typedef struct {
    u8 pad_0[0x2];
    s16 unk_2;  // 1 loads, 0 stores
    s16 unk_4;  // 6 loads, 0 stores
    s16 unk_6;  // 1 loads, 0 stores
    u32 unk_8;  // 8 loads, 0 stores
    s16 unk_C;  // 8 loads, 0 stores
    s16 unk_E;  // 9 loads, 0 stores
    u32 unk_10;  // 3 loads, 0 stores
    u32 unk_14;  // 8 loads, 0 stores
    u32 unk_18;  // 3 loads, 0 stores
    s16 unk_1C;  // 1 loads, 0 stores
    u8 pad_1E[0x2];
    s16 unk_20;  // 1 loads, 0 stores
    s16 unk_22;  // 1 loads, 0 stores
} Obj_1_bss_8F568_AtC;
typedef struct {
    u8 unk_0;  // 1 loads, 1 stores
    u8 pad_1[0x3];
    f32 unk_4;  // 6 loads, 2 stores
    f32 unk_8;  // 3 loads, 1 stores
    Obj_1_bss_8F568_AtC *unk_C;  // 2 loads, 1 stores
} Obj_1_bss_8F568;
extern Obj_1_bss_8F568 lbl_1_bss_8F568;

// lbl_1_bss_8EF20: .bss size 0x48, 5 refs from ranking.c
typedef struct {
    f32 unk_0;  // 12 loads, 6 stores
    u32 unk_4;  // 2 loads, 0 stores
    f64 unk_8;  // 8 loads, 6 stores
    f64 unk_10;  // 8 loads, 6 stores
    u16 unk_18;  // 10 loads, 6 stores
    u8 unk_1A;  // 2 loads, 0 stores
    u8 pad_1B[0x5];
    f64 unk_20;  // 8 loads, 6 stores
    f64 unk_28;  // 8 loads, 6 stores
    f64 unk_30;  // 9 loads, 10 stores
    u32 unk_38;  // 2 loads, 0 stores
    u8 pad_3C[0x16];
    u8 unk_52;  // 2 loads, 0 stores
    u8 pad_53[0x15];
    u8 unk_68;  // 0 loads, 4 stores
    u8 pad_69[0x7];
    u32 unk_70;  // 1 loads, 0 stores
    u8 pad_74[0x2C];
    u8 unk_A0;  // 0 loads, 2 stores
    u8 pad_A1[0x7];
    u32 unk_A8;  // 1 loads, 0 stores
    u8 pad_AC[0x2C];
    u8 unk_D8;  // 0 loads, 2 stores
    u8 pad_D9[0x7];
    u32 unk_E0;  // 1 loads, 0 stores
    u8 pad_E4[0x2C];
    u8 unk_110;  // 0 loads, 2 stores
} Obj_1_bss_8EF20_At0;
typedef struct {
    Obj_1_bss_8EF20_At0 *unk_0;  // 17 loads, 3 stores
    u8 pad_4[0x3C];
    u32 unk_40;  // 1 loads, 2 stores
    u8 pad_44[0x4];
} Obj_1_bss_8EF20;
extern Obj_1_bss_8EF20 lbl_1_bss_8EF20;

// lbl_1_data_4C810: .data size 0xF0, 5 refs from ranking.c (own data block)
typedef struct {
    u32 unk_0;  // 2 loads, 0 stores
    u32 unk_4;  // 3 loads, 0 stores
    s16 unk_8;  // 2 loads, 1 stores
    u8 pad_A[0x1E];
    s16 unk_28;  // 4 loads, 3 stores
    s16 unk_2A;  // 5 loads, 2 stores
    u8 unk_2C;  // 2 loads, 0 stores
    u8 pad_2D[0x3];
    u32 unk_30;  // 1 loads, 0 stores
    u32 unk_34;  // 1 loads, 2 stores
    u32 unk_38;  // 1 loads, 1 stores
    u8 pad_3C[0xB4];
} Obj_1_data_4C810;
extern Obj_1_data_4C810 lbl_1_data_4C810;

// lbl_1_bss_8F588: .bss size 0x2F0, 3 refs from ranking.c
extern u8 lbl_1_bss_8F588[0x2F0];

// lbl_1_data_49B08: .data size 0xA, 2 refs from ranking.c (own data block)
extern u8 lbl_1_data_49B08[0xA];

// lbl_1_data_FCD4: .data size 0x1D60, 2 refs from ranking.c
typedef struct {
    u8 pad_0[0x4];
    u32 unk_4;  // 3 loads, 0 stores
    u8 pad_8[0x4];
    u32 unk_C;  // 6 loads, 0 stores
} Obj_1_data_FCD4_At20;
typedef struct {
    u32 unk_0;  // 14 loads, 2 stores
    u32 unk_4;  // 2 loads, 0 stores
    u8 pad_8[0x18];
    Obj_1_data_FCD4_At20 *unk_20;  // 10 loads, 0 stores
    u8 unk_24;  // 13 loads, 0 stores
    u8 pad_25[0x1D3B];
} Obj_1_data_FCD4;
extern Obj_1_data_FCD4 lbl_1_data_FCD4;

// lbl_1_bss_8F578: .bss size 0x4, 2 refs from ranking.c
extern u32 lbl_1_bss_8F578;

// lbl_1_bss_8F3E0: .bss size 0x4, 2 refs from ranking.c
extern u32 lbl_1_bss_8F3E0;

// lbl_1_bss_8F3E4: .bss size 0x18, 2 refs from ranking.c
typedef struct {
    u32 unk_0;  // 1 loads, 1 stores
    u8 pad_4[0x14];
} Obj_1_bss_8F3E4;
extern Obj_1_bss_8F3E4 lbl_1_bss_8F3E4;

// jumptable_1_data_4C7B0: .data size 0x1C, 1 refs from ranking.c (own data block)
extern u8 jumptable_1_data_4C7B0[0x1C];

// jumptable_1_data_4C794: .data size 0x1C, 1 refs from ranking.c (own data block)
extern u8 jumptable_1_data_4C794[0x1C];

// lbl_1_data_49B20: .data size 0x8, 1 refs from ranking.c (own data block)
extern u32 lbl_1_data_49B20[2];

// lbl_1_data_4C900: .data size 0x2E, 1 refs from ranking.c (own data block)
extern u8 lbl_1_data_4C900[0x2E];

// lbl_1_data_49B14: .data size 0x9, 1 refs from ranking.c (own data block)
extern u8 lbl_1_data_49B14[0x9];

// lbl_1_data_4C788: .data size 0xC, 1 refs from ranking.c (own data block)
extern u8 lbl_1_data_4C788[0xC];

#endif  // REL_MAIN_REL_RANKING_H
