#ifndef REL_MAIN_REL_RELOCATION_H
#define REL_MAIN_REL_RELOCATION_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu relocation.c`: globals of relocation.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_bss_6F5F0: .bss size 0x4, 5 refs from relocation.c
extern u32 lbl_1_bss_6F5F0;

// lbl_1_data_341B8: .data size 0x4, 5 refs from relocation.c (own data block)
typedef struct {
    u32 unk_0;  // 2 loads, 5 stores
    u8 unk_4;  // 6 loads, 7 stores
    u8 unk_5;  // 4 loads, 4 stores
    s16 unk_6;  // 3 loads, 7 stores
} Obj_1_data_341B8_Target;
extern Obj_1_data_341B8_Target *lbl_1_data_341B8;

// lbl_1_data_34140: .data size 0x54, 1 refs from relocation.c (own data block)
extern u8 lbl_1_data_34140[0x54];

// lbl_1_data_34194: .data size 0x1F, 1 refs from relocation.c (own data block)
extern u8 lbl_1_data_34194[0x1F];

#endif  // REL_MAIN_REL_RELOCATION_H
