#ifndef REL_MAIN_REL_REP_MEMCARD_H
#define REL_MAIN_REL_REP_MEMCARD_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu rep_memcard.c`: globals of rep_memcard.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_bss_8EDF0: .bss size 0x130, 11 refs from rep_memcard.c
typedef struct {
    u8 unk_0;  // 3 loads, 0 stores
    u8 unk_1;  // 1 loads, 0 stores
} Obj_1_bss_8EDF0_At10;
typedef struct {
    u32 unk_0;  // 3 loads, 2 stores
    u32 unk_4;  // 2 loads, 5 stores
    u32 unk_8;  // 4 loads, 3 stores
    u32 unk_C;  // 0 loads, 2 stores
    Obj_1_bss_8EDF0_At10 *unk_10;  // 5 loads, 9 stores
    u32 unk_14;  // 9 loads, 8 stores
    u32 unk_18;  // 3 loads, 2 stores
    u32 unk_1C;  // 8 loads, 5 stores
    u32 unk_20;  // 1 loads, 2 stores
    u32 unk_24;  // 1 loads, 2 stores
    f32 unk_28;  // 1 loads, 2 stores
    f32 unk_2C;  // 1 loads, 2 stores
    u32 unk_30;  // 1 loads, 2 stores
    u8 unk_34;  // 0 loads, 6 stores
    u8 unk_35;  // 0 loads, 1 stores
    u8 pad_36[0xFA];
} Obj_1_bss_8EDF0;
extern Obj_1_bss_8EDF0 lbl_1_bss_8EDF0;

// lbl_1_bss_8ED90: .bss size 0x4, 5 refs from rep_memcard.c
extern u32 lbl_1_bss_8ED90;

// lbl_1_bss_8ED94: .bss size 0xC, 3 refs from rep_memcard.c
typedef struct {
    u32 unk_0;  // 2 loads, 3 stores
    u8 pad_4[0x8];
} Obj_1_bss_8ED94;
extern Obj_1_bss_8ED94 lbl_1_bss_8ED94;

// lbl_1_data_49AC8: .data size 0xE, 3 refs from rep_memcard.c (own data block)
extern u8 lbl_1_data_49AC8[0xE];

// lbl_1_data_49AB4: .data size 0x14, 2 refs from rep_memcard.c
typedef struct {
    u32 unk_0;  // 1 loads, 8 stores
    u8 pad_4[0x10];
} Obj_1_data_49AB4;
extern Obj_1_data_49AB4 lbl_1_data_49AB4;

// jumptable_1_data_49AD8: .data size 0x30, 1 refs from rep_memcard.c (own data block)
extern u8 jumptable_1_data_49AD8[0x30];

#endif  // REL_MAIN_REL_REP_MEMCARD_H
