#ifndef REL_MAIN_REL_RESET_H
#define REL_MAIN_REL_RESET_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu reset.c`: globals of reset.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_bss_7AD48: .bss size 0x10, 4 refs from reset.c
typedef struct {
    u8 unk_0;  // 3 loads, 5 stores
    u8 unk_1;  // 1 loads, 0 stores
    u8 unk_2;  // 2 loads, 2 stores
    u8 pad_3[0x1];
    u32 unk_4;  // 2 loads, 0 stores
    u8 unk_8;  // 2 loads, 2 stores
    u8 unk_9;  // 1 loads, 2 stores
    u8 unk_A;  // 2 loads, 4 stores
    u8 pad_B[0x5];
} Obj_1_bss_7AD48;
extern Obj_1_bss_7AD48 lbl_1_bss_7AD48;

// lbl_1_data_3DBC0: .data size 0x8, 2 refs from reset.c (own data block)
extern u32 lbl_1_data_3DBC0;

// lbl_1_data_3DBC8: .data size 0xE, 2 refs from reset.c (own data block)
extern u8 lbl_1_data_3DBC8[0xE];

#endif  // REL_MAIN_REL_RESET_H
