#ifndef REL_MAIN_REL_ROB_H
#define REL_MAIN_REL_ROB_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu rob.c`: globals of rob.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_data_209C0: .data size 0x8, 4 refs from rob.c
extern u32 lbl_1_data_209C0;

// lbl_1_data_27C00: .data size 0xE0, 2 refs from rob.c (own data block)
extern u8 lbl_1_data_27C00[0xE0];

// lbl_1_bss_6EAD0: .bss size 0x708, 2 refs from rob.c
typedef struct {
    u32 unk_0;  // 23 loads, 0 stores
    u32 unk_4;  // 9 loads, 0 stores
} Obj_1_bss_6EAD0_At0;
typedef struct {
    Obj_1_bss_6EAD0_At0 *unk_0;  // 34 loads, 0 stores
    u8 pad_4[0x704];
} Obj_1_bss_6EAD0;
extern Obj_1_bss_6EAD0 lbl_1_bss_6EAD0;

// lbl_1_data_27D90: .data size 0x50, 1 refs from rob.c (own data block)
extern u8 lbl_1_data_27D90[0x50];

#endif  // REL_MAIN_REL_ROB_H
