#ifndef REL_MAIN_REL_SHADOWMAP_H
#define REL_MAIN_REL_SHADOWMAP_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu shadowmap.c`: globals of shadowmap.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_data_1C670: .data size 0x1C, 6 refs from shadowmap.c (own data block)
typedef struct {
    u8 unk_0;  // 6 loads, 4 stores
    u8 pad_1[0x3];
    u32 unk_4;  // 6 loads, 4 stores
    u32 unk_8;  // 6 loads, 4 stores
    u32 unk_C;  // 6 loads, 4 stores
    u32 unk_10;  // 6 loads, 4 stores
    u32 unk_14;  // 5 loads, 2 stores
    u32 unk_18;  // 3 loads, 2 stores
} Obj_1_data_1C670;
extern Obj_1_data_1C670 lbl_1_data_1C670;

// lbl_1_data_1C660: .data size 0xC, 2 refs from shadowmap.c (own data block)
extern u8 lbl_1_data_1C660[0xC];

#endif  // REL_MAIN_REL_SHADOWMAP_H
