#ifndef REL_MAIN_REL_SOM_H
#define REL_MAIN_REL_SOM_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu som.c`: globals of som.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_data_5194: .data size 0x34, 1 refs from som.c (own data block)
extern u8 lbl_1_data_5194[0x34];

// lbl_1_data_5190: .data size 0x1, 1 refs from som.c (own data block)
extern u8 lbl_1_data_5190;

// lbl_1_data_5188: .data size 0x6, 1 refs from som.c (own data block)
extern u32 lbl_1_data_5188;

#endif  // REL_MAIN_REL_SOM_H
