#ifndef REL_MAIN_REL_SOUND_H
#define REL_MAIN_REL_SOUND_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu sound.c`: globals of sound.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_bss_6F1DC: .bss size 0x4, 12 refs from sound.c
extern u32 lbl_1_bss_6F1DC;

// lbl_1_bss_6F1D8: .bss size 0x1, 9 refs from sound.c
extern u8 lbl_1_bss_6F1D8;

// lbl_1_data_2D93C: .data size 0xC4, 5 refs from sound.c
typedef struct {
    u8 pad_0[0x84];
    s16 unk_84;  // 5 loads, 0 stores
    u8 pad_86[0x3E];
} Obj_1_data_2D93C;
extern Obj_1_data_2D93C lbl_1_data_2D93C;

// lbl_1_data_2D7B8: .data size 0x184, 5 refs from sound.c
typedef struct {
    u8 pad_0[0x108];
    u32 unk_108;  // 1 loads, 0 stores
    u8 pad_10C[0x78];
} Obj_1_data_2D7B8;
extern Obj_1_data_2D7B8 lbl_1_data_2D7B8;

// lbl_1_data_33F1C: .data size 0x8, 4 refs from sound.c (own data block)
extern u32 lbl_1_data_33F1C;

// lbl_1_bss_962: .bss size 0x2, 3 refs from sound.c
extern s16 lbl_1_bss_962;

// lbl_1_bss_6EAC6: .bss size 0xA, 3 refs from sound.c
typedef struct {
    u8 unk_0;  // 6 loads, 0 stores
    u8 pad_1[0x9];
} Obj_1_bss_6EAC6;
extern Obj_1_bss_6EAC6 lbl_1_bss_6EAC6;

// lbl_1_bss_6F1E0: .bss size 0x1, 3 refs from sound.c
extern u8 lbl_1_bss_6F1E0;

// lbl_1_bss_8CA24: .bss size 0x1, 3 refs from sound.c
extern u8 lbl_1_bss_8CA24;

// lbl_1_bss_8B5F0: .bss size 0x1, 3 refs from sound.c
extern u8 lbl_1_bss_8B5F0;

// lbl_1_bss_8B5F1: .bss size 0x1, 3 refs from sound.c
extern u8 lbl_1_bss_8B5F1;

// lbl_1_bss_6EA9C: .bss size 0x8, 2 refs from sound.c
extern u32 lbl_1_bss_6EA9C;

// lbl_1_bss_6EAD0: .bss size 0x708, 2 refs from sound.c
typedef struct {
    u32 unk_0;  // 23 loads, 0 stores
    u32 unk_4;  // 9 loads, 0 stores
} Obj_1_bss_6EAD0_At0;
typedef struct {
    Obj_1_bss_6EAD0_At0 *unk_0;  // 34 loads, 0 stores
    u8 pad_4[0x704];
} Obj_1_bss_6EAD0;
extern Obj_1_bss_6EAD0 lbl_1_bss_6EAD0;

// jumptable_1_data_33F68: .data size 0x44, 1 refs from sound.c (own data block)
extern u8 jumptable_1_data_33F68[0x44];

// jumptable_1_data_33FAC: .data size 0x44, 1 refs from sound.c (own data block)
extern u8 jumptable_1_data_33FAC[0x44];

// lbl_1_data_33FF0: .data size 0x150, 1 refs from sound.c (own data block)
extern u8 lbl_1_data_33FF0[0x150];

#endif  // REL_MAIN_REL_SOUND_H
