#ifndef REL_MAIN_REL_SPLINE_H
#define REL_MAIN_REL_SPLINE_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu spline.c`: globals of spline.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_bss_84428: .bss size 0x28, 4 refs from spline.c
typedef struct {
    u32 unk_0;  // 1 loads, 1 stores
    s16 unk_4;  // 2 loads, 3 stores
    s16 unk_6;  // 1 loads, 1 stores
    s16 unk_8;  // 1 loads, 1 stores
    s16 unk_A;  // 1 loads, 1 stores
    u16 unk_C;  // 0 loads, 1 stores
    u8 pad_E[0xA];
    f32 unk_18;  // 1 loads, 0 stores
    f32 unk_1C;  // 1 loads, 0 stores
    f32 unk_20;  // 1 loads, 0 stores
    f32 unk_24;  // 2 loads, 0 stores
} Obj_1_bss_84428;
extern Obj_1_bss_84428 lbl_1_bss_84428;

// lbl_1_data_3E8F0: .data size 0x1, 3 refs from spline.c (own data block)
extern u8 lbl_1_data_3E8F0;

// lbl_1_bss_7F028: .bss size 0x1, 3 refs from spline.c
extern u8 lbl_1_bss_7F028;

// lbl_1_bss_7F02C: .bss size 0x10, 3 refs from spline.c
typedef struct {
    u8 unk_0;  // 2 loads, 11 stores
    u8 pad_1[0x1];
    u16 unk_2;  // 5 loads, 5 stores
    u8 pad_4[0xC];
} Obj_1_bss_7F02C;
extern Obj_1_bss_7F02C lbl_1_bss_7F02C;

// lbl_1_bss_718E0: .bss size 0x59E8, 3 refs from spline.c
typedef struct {
    u16 unk_0;  // 0 loads, 1 stores
    u8 unk_2;  // 2 loads, 1 stores
    u8 unk_3;  // 1 loads, 1 stores
    u8 pad_4[0x2];
    u16 unk_6;  // 0 loads, 1 stores
    u8 pad_8[0x198];
    u16 unk_1A0;  // 0 loads, 1 stores
    u8 pad_1A2[0x537E];
    u16 unk_5520;  // 0 loads, 1 stores
    u8 pad_5522[0x1];
    u8 unk_5523;  // 1 loads, 0 stores
    u8 pad_5524[0x4C4];
} Obj_1_bss_718E0;
extern Obj_1_bss_718E0 lbl_1_bss_718E0;

// lbl_1_bss_7F03C: .bss size 0x10, 2 refs from spline.c
typedef struct {
    u8 unk_0;  // 3 loads, 4 stores
    u8 pad_1[0x1];
    u16 unk_2;  // 2 loads, 4 stores
    u8 pad_4[0xC];
} Obj_1_bss_7F03C;
extern Obj_1_bss_7F03C lbl_1_bss_7F03C;

// jumptable_1_data_3E8F4: .data size 0x1C, 1 refs from spline.c (own data block)
extern u8 jumptable_1_data_3E8F4[0x1C];

// lbl_1_data_3E8E0: .data size 0x9, 1 refs from spline.c (own data block)
extern u8 lbl_1_data_3E8E0[0x9];

// lbl_1_data_3EED0: .data size 0x60, 1 refs from spline.c (own data block)
typedef struct {
    u8 unk_0;  // 1 loads, 0 stores
    u8 unk_1;  // 1 loads, 0 stores
    u8 unk_2;  // 1 loads, 0 stores
    u8 unk_3;  // 1 loads, 0 stores
    u8 pad_4[0x5C];
} Obj_1_data_3EED0;
extern Obj_1_data_3EED0 lbl_1_data_3EED0;

// lbl_1_data_3EF30: .data size 0x60, 1 refs from spline.c (own data block)
typedef struct {
    u32 unk_0;  // 4 loads, 0 stores
    u32 unk_4;  // 4 loads, 0 stores
    u32 unk_8;  // 4 loads, 0 stores
    u8 pad_C[0x54];
} Obj_1_data_3EF30;
extern Obj_1_data_3EF30 lbl_1_data_3EF30;

// lbl_1_data_3E910: .data size 0xA0, 1 refs from spline.c (own data block)
extern u8 lbl_1_data_3E910[0xA0];

#endif  // REL_MAIN_REL_SPLINE_H
