/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern u32 lbl_17_bss_198[95];
extern u8 lbl_17_bss_314[64];



__declspec(section ".data") u8 lbl_17_bss_314[64] __attribute__((aligned(4)));



__declspec(section ".data") u32 lbl_17_bss_198[95] __attribute__((aligned(8)));
