/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern u32 lbl_17_bss_150[4];
extern f32 lbl_17_bss_160[4];



__declspec(section ".data") f32 lbl_17_bss_160[4] __attribute__((aligned(4)));



__declspec(section ".data") u32 lbl_17_bss_150[4] __attribute__((aligned(8)));
