/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"
#include "rel/main_rel/bg_cas.h"

extern u8 lbl_1_bss_850E0[256];
extern u8 lbl_1_bss_851E0[36];
extern u8 lbl_1_bss_85204[0x20];
extern u8 lbl_1_bss_85224[0x2C];



__declspec(section ".data") u8 lbl_1_bss_85224[0x2C] __attribute__((aligned(4)));



__declspec(section ".data") u8 lbl_1_bss_85204[0x20] __attribute__((aligned(4)));



__declspec(section ".data") u8 lbl_1_bss_851E0[36] __attribute__((aligned(32)));



__declspec(section ".data") u8 lbl_1_bss_850E0[256] __attribute__((aligned(32)));
