/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"
#include "rel/main_rel/mdlload.h"

extern u8 lbl_1_bss_3BC0[0x20];



__declspec(section ".data") u8 lbl_1_bss_3BC0[0x20] __attribute__((aligned(32)));
