/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern u8 lbl_1_bss_3E000[32];



__declspec(section ".data") u8 lbl_1_bss_3E000[32] __attribute__((aligned(32)));
