/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern u8 lbl_1_bss_8E6B0[308];



__declspec(section ".data") u8 lbl_1_bss_8E6B0[308] __attribute__((aligned(16)));
