/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"
#include "rel/main_rel/live_camera.h"

extern u8 lbl_1_bss_1800[0x10];
extern u8 lbl_1_bss_1810[8984];



__declspec(section ".data") u8 lbl_1_bss_1810[8984] __attribute__((aligned(16)));



__declspec(section ".data") u8 lbl_1_bss_1800[0x10] __attribute__((aligned(32)));
