/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern u8 lbl_1_bss_7EA00[56];
extern u32 lbl_1_bss_7EA38[159];



__declspec(section ".data") u32 lbl_1_bss_7EA38[159] __attribute__((aligned(8)));



__declspec(section ".data") u8 lbl_1_bss_7EA00[56] __attribute__((aligned(32)));
