/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern f32 lbl_1_bss_1160[403];



__declspec(section ".data") f32 lbl_1_bss_1160[403] __attribute__((aligned(4)));
