/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern u8 lbl_1_bss_38218[568];



__declspec(section ".data") u8 lbl_1_bss_38218[568] __attribute__((aligned(8)));
