/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern u16 lbl_1_bss_26C68[35526];



__declspec(section ".data") u16 lbl_1_bss_26C68[35526] __attribute__((aligned(8)));
