/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern u32 lbl_1_bss_7ED58[158];



__declspec(section ".data") u32 lbl_1_bss_7ED58[158] __attribute__((aligned(8)));
