/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern u8 lbl_1_bss_7AC90[12];



__declspec(section ".data") u8 lbl_1_bss_7AC90[12] __attribute__((aligned(16)));
