/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"
#include "rel/main_rel/font.h"

extern u8 lbl_1_bss_4E6B0[0x20];



__declspec(section ".data") u8 lbl_1_bss_4E6B0[0x20] __attribute__((aligned(16)));
