/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern u8 lbl_1_bss_7AD58[8];



__declspec(section ".data") u8 lbl_1_bss_7AD58[8] __attribute__((aligned(8)));
