/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"
#include "rel/main_rel/font.h"

extern u8 lbl_1_bss_6C710[0x88];



__declspec(section ".data") u8 lbl_1_bss_6C710[0x88] __attribute__((aligned(16)));
