/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"
#include "rel/main_rel/font.h"

extern u8 lbl_1_bss_4BA60[0x20];
extern u8 lbl_1_bss_4BA80[0xB0];



__declspec(section ".data") u8 lbl_1_bss_4BA80[0xB0] __attribute__((aligned(32)));



__declspec(section ".data") u8 lbl_1_bss_4BA60[0x20] __attribute__((aligned(32)));
