/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern u32 lbl_1_bss_7AD08[7];
extern u32 lbl_1_bss_7AD24[9];



__declspec(section ".data") u32 lbl_1_bss_7AD24[9] __attribute__((aligned(4)));



__declspec(section ".data") u32 lbl_1_bss_7AD08[7] __attribute__((aligned(8)));
