/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern u16 lbl_1_bss_990[28];



__declspec(section ".data") u16 lbl_1_bss_990[28] __attribute__((aligned(16)));
