/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern u16 lbl_12_bss_63B0[32];



__declspec(section ".data") u16 lbl_12_bss_63B0[32] __attribute__((aligned(16)));
