/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern float lbl_12_bss_DB0[64][64];



__declspec(section ".data") float lbl_12_bss_DB0[64][64] __attribute__((aligned(16)));
