/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern double lbl_12_bss_BB0[64];



__declspec(section ".data") double lbl_12_bss_BB0[64] __attribute__((aligned(8)));
