/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern u8 lbl_12_bss_7A50[520];



__declspec(section ".data") u8 lbl_12_bss_7A50[520] __attribute__((aligned(16)));
