/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern u8 lbl_12_bss_9710[73760];



__declspec(section ".data") u8 lbl_12_bss_9710[73760] __attribute__((aligned(16)));
