#ifndef REL_MAIN_GLOBALS_H
#define REL_MAIN_GLOBALS_H

#include "types.h"

// Generated by `fzgx headers --module main`: layouts recovered from every access in the
// module's disassembly (matched or not). Field names are offsets until the librarian names them;
// offsets and widths are facts, names are not. Regenerate rather than hand-edit padding.

// lbl_801A6C80: .sbss size 0x8, referenced by 61 functions, shape {}
extern u32 lbl_801A6C80;

// lbl_80177960: .bss size 0x220, referenced by 49 functions, shape {'object': 326}
// object reached through lbl_80177960.unk_88
typedef struct {
    u16 unk_0;  // 1 loads, 1 stores
    u8 pad_2[0x4];
    u16 unk_6;  // 2 loads, 2 stores
    u16 unk_8;  // 1 loads, 1 stores
} Obj_80177960_At88;
// object reached through lbl_80177960.unk_C0
typedef struct {
    u8 pad_0[0x4];
    u32 unk_4;  // 1 loads, 0 stores
    u32 unk_8;  // 2 loads, 2 stores
    u32 unk_C;  // 5 loads, 2 stores
    u16 unk_10;  // 3 loads, 2 stores
} Obj_80177960_AtC0;
typedef struct {
    u32 unk_0;  // 14 loads, 4 stores
    u32 unk_4;  // 6 loads, 7 stores
    u16 unk_8;  // 1 loads, 1 stores
    u8 pad_A[0x2];
    u32 unk_C;  // 15 loads, 1 stores
    u16 unk_10;  // 4 loads, 1 stores
    u8 pad_12[0x2];
    u32 unk_14;  // 4 loads, 1 stores
    u8 unk_18;  // 2 loads, 0 stores
    u8 unk_19;  // 2 loads, 0 stores
    u8 unk_1A;  // 2 loads, 0 stores
    u8 unk_1B;  // 2 loads, 0 stores
    u8 unk_1C;  // 2 loads, 0 stores
    u8 unk_1D;  // 2 loads, 0 stores
    u8 unk_1E;  // 2 loads, 0 stores
    u8 unk_1F;  // 2 loads, 0 stores
    u8 pad_20[0x4];
    u32 unk_24;  // 5 loads, 6 stores
    u32 unk_28;  // 2 loads, 3 stores
    u32 unk_2C;  // 10 loads, 10 stores
    u16 unk_30;  // 0 loads, 1 stores
    u16 unk_32;  // 1 loads, 2 stores
    u8 unk_34;  // 0 loads, 2 stores
    u8 unk_35;  // 0 loads, 1 stores
    u16 unk_36;  // 1 loads, 1 stores
    u8 pad_38[0x4];
    u32 unk_3C;  // 0 loads, 2 stores
    u32 unk_40;  // 0 loads, 1 stores
    u32 unk_44;  // 0 loads, 1 stores
    u8 pad_48[0xC];
    u16 unk_54;  // 0 loads, 1 stores
    u8 pad_56[0x2];
    u32 unk_58;  // 0 loads, 1 stores
    u32 unk_5C;  // 0 loads, 1 stores
    u32 unk_60;  // 0 loads, 1 stores
    u32 unk_64;  // 0 loads, 1 stores
    u8 pad_68[0x18];
    u32 unk_80;  // 19 loads, 1 stores
    u32 unk_84;  // 4 loads, 4 stores
    Obj_80177960_At88 *unk_88;  // 5 loads, 4 stores
    u8 pad_8C[0x8];
    u8 unk_94;  // 4 loads, 3 stores
    u8 unk_95;  // 0 loads, 3 stores
    u8 unk_96;  // 0 loads, 3 stores
    u8 unk_97;  // 0 loads, 2 stores
    u8 unk_98;  // 0 loads, 2 stores
    u8 pad_99[0x7];
    u32 unk_A0;  // 4 loads, 3 stores
    u32 unk_A4;  // 4 loads, 3 stores
    u32 unk_A8;  // 1 loads, 4 stores
    u32 unk_AC;  // 2 loads, 4 stores
    u32 unk_B0;  // 10 loads, 4 stores
    u32 unk_B4;  // 7 loads, 4 stores
    u32 unk_B8;  // 3 loads, 2 stores
    u16 unk_BC;  // 1 loads, 0 stores
    u16 unk_BE;  // 2 loads, 1 stores
    Obj_80177960_AtC0 *unk_C0;  // 5 loads, 0 stores
    u32 unk_C4;  // 1 loads, 2 stores
    u32 unk_C8;  // 2 loads, 3 stores
    u32 unk_CC;  // 4 loads, 7 stores
    u32 unk_D0;  // 14 loads, 10 stores
    u32 unk_D4;  // 2 loads, 4 stores
    u32 unk_D8;  // 4 loads, 6 stores
    u32 unk_DC;  // 1 loads, 7 stores
    u8 pad_E0[0x28];
    u32 unk_108;  // 1 loads, 1 stores
    u32 unk_10C;  // 6 loads, 3 stores
    u8 pad_110[0x110];
} Obj_80177960;
extern Obj_80177960 lbl_80177960;

// lbl_801A6D38: .sbss size 0x8, referenced by 49 functions, shape {}
extern u32 lbl_801A6D38;

// lbl_8018FEB0: .bss size 0x30, referenced by 22 functions, shape {'object': 227}
typedef struct {
    u32 unk_0;  // 4 loads, 2 stores
    u32 unk_4;  // 44 loads, 22 stores
    u32 unk_8;  // 22 loads, 22 stores
    u8 pad_C[0x20];
    u32 unk_2C;  // 1 loads, 2 stores
} Obj_8018FEB0;
extern Obj_8018FEB0 lbl_8018FEB0;

#endif  // REL_MAIN_GLOBALS_H
