/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern u32 lbl_80187118[6];
extern u8 lbl_80187130[512];



__declspec(section ".data") u8 lbl_80187130[512] __attribute__((aligned(8)));



__declspec(section ".data") u32 lbl_80187118[6] __attribute__((aligned(8)));
