/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern u32 lbl_8015BE40[40];
extern u32 lbl_8015BEE0[8];



__declspec(section ".data") u32 lbl_8015BEE0[8] __attribute__((aligned(8)));



__declspec(section ".data") u32 lbl_8015BE40[40] __attribute__((aligned(8)));
