/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern u32 lbl_80187380[16];



__declspec(section ".data") u32 lbl_80187380[16] __attribute__((aligned(8)));
