/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern u32 lbl_3_bss_6DD78[42];



__declspec(section ".data") u32 lbl_3_bss_6DD78[42] __attribute__((aligned(8)));
