/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern u8 lbl_3_bss_A1778[12];



__declspec(section ".data") u8 lbl_3_bss_A1778[12] __attribute__((aligned(8)));
