/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern u8 lbl_3_bss_7E240[1200];



__declspec(section ".data") u8 lbl_3_bss_7E240[1200] __attribute__((aligned(32)));
