/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern u8 lbl_15_bss_3F8[136];



__declspec(section ".data") u8 lbl_15_bss_3F8[136] __attribute__((aligned(8)));
