/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern f32 lbl_15_bss_88[5];
extern u32 lbl_15_bss_9C[13];



__declspec(section ".data") u32 lbl_15_bss_9C[13] __attribute__((aligned(4)));



__declspec(section ".data") f32 lbl_15_bss_88[5] __attribute__((aligned(4)));
