/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"
#include "rel/pilotpoint/pilotpoint.h"

extern u8 lbl_14_bss_180[0x81C0];



__declspec(section ".data") u8 lbl_14_bss_180[0x81C0] __attribute__((aligned(32)));
